!#/bin/bash
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/AUST/2016Census_G01_AUS.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/AUST/2016Census_G02_AUS.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/AUST/2016Census_G04A_AUS.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/AUST/2016Census_G04B_AUS.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/AUST/2016Census_G05_AUS.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/AUST/2016Census_G07_AUS.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/AUST/2016Census_G08_AUS.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/AUST/2016Census_G25_AUS.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/AUST/2016Census_G27_AUS.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/AUST/2016Census_G28_AUS.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/AUST/2016Census_G29_AUS.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/AUST/2016Census_G30_AUS.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/AUST/2016Census_G31_AUS.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/AUST/2016Census_G59_AUS.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/CED/AUST/2016Census_G01_AUS_CED.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/CED/AUST/2016Census_G02_AUS_CED.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/CED/AUST/2016Census_G04A_AUS_CED.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/CED/AUST/2016Census_G04B_AUS_CED.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/CED/AUST/2016Census_G05_AUS_CED.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/CED/AUST/2016Census_G07_AUS_CED.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/CED/AUST/2016Census_G08_AUS_CED.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/CED/AUST/2016Census_G25_AUS_CED.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/CED/AUST/2016Census_G27_AUS_CED.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/CED/AUST/2016Census_G28_AUS_CED.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/CED/AUST/2016Census_G29_AUS_CED.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/CED/AUST/2016Census_G30_AUS_CED.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/CED/AUST/2016Census_G31_AUS_CED.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/CED/AUST/2016Census_G59_AUS_CED.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/GCCSA/AUST/2016Census_G01_AUS_GCCSA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/GCCSA/AUST/2016Census_G02_AUS_GCCSA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/GCCSA/AUST/2016Census_G04A_AUS_GCCSA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/GCCSA/AUST/2016Census_G04B_AUS_GCCSA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/GCCSA/AUST/2016Census_G05_AUS_GCCSA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/GCCSA/AUST/2016Census_G07_AUS_GCCSA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/GCCSA/AUST/2016Census_G08_AUS_GCCSA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/GCCSA/AUST/2016Census_G25_AUS_GCCSA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/GCCSA/AUST/2016Census_G27_AUS_GCCSA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/GCCSA/AUST/2016Census_G28_AUS_GCCSA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/GCCSA/AUST/2016Census_G29_AUS_GCCSA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/GCCSA/AUST/2016Census_G30_AUS_GCCSA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/GCCSA/AUST/2016Census_G31_AUS_GCCSA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/GCCSA/AUST/2016Census_G59_AUS_GCCSA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/LGA/AUST/2016Census_G01_AUS_LGA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/LGA/AUST/2016Census_G02_AUS_LGA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/LGA/AUST/2016Census_G04A_AUS_LGA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/LGA/AUST/2016Census_G04B_AUS_LGA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/LGA/AUST/2016Census_G05_AUS_LGA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/LGA/AUST/2016Census_G07_AUS_LGA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/LGA/AUST/2016Census_G08_AUS_LGA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/LGA/AUST/2016Census_G25_AUS_LGA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/LGA/AUST/2016Census_G27_AUS_LGA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/LGA/AUST/2016Census_G28_AUS_LGA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/LGA/AUST/2016Census_G29_AUS_LGA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/LGA/AUST/2016Census_G30_AUS_LGA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/LGA/AUST/2016Census_G31_AUS_LGA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/LGA/AUST/2016Census_G59_AUS_LGA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/POA/AUST/2016Census_G01_AUS_POA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/POA/AUST/2016Census_G02_AUS_POA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/POA/AUST/2016Census_G04A_AUS_POA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/POA/AUST/2016Census_G04B_AUS_POA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/POA/AUST/2016Census_G05_AUS_POA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/POA/AUST/2016Census_G07_AUS_POA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/POA/AUST/2016Census_G08_AUS_POA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/POA/AUST/2016Census_G25_AUS_POA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/POA/AUST/2016Census_G27_AUS_POA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/POA/AUST/2016Census_G28_AUS_POA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/POA/AUST/2016Census_G29_AUS_POA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/POA/AUST/2016Census_G30_AUS_POA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/POA/AUST/2016Census_G31_AUS_POA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/POA/AUST/2016Census_G59_AUS_POA.csv


./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/RA/AUST/2016Census_G01_AUS_RA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/RA/AUST/2016Census_G02_AUS_RA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/RA/AUST/2016Census_G04A_AUS_RA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/RA/AUST/2016Census_G04B_AUS_RA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/RA/AUST/2016Census_G05_AUS_RA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/RA/AUST/2016Census_G07_AUS_RA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/RA/AUST/2016Census_G08_AUS_RA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/RA/AUST/2016Census_G25_AUS_RA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/RA/AUST/2016Census_G27_AUS_RA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/RA/AUST/2016Census_G28_AUS_RA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/RA/AUST/2016Census_G29_AUS_RA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/RA/AUST/2016Census_G30_AUS_RA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/RA/AUST/2016Census_G31_AUS_RA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/RA/AUST/2016Census_G59_AUS_RA.csv

./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA2/AUST/2016Census_G01_AUS_SA2.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA2/AUST/2016Census_G02_AUS_SA2.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA2/AUST/2016Census_G04A_AUS_SA2.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA2/AUST/2016Census_G04B_AUS_SA2.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA2/AUST/2016Census_G05_AUS_SA2.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA2/AUST/2016Census_G07_AUS_SA2.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA2/AUST/2016Census_G08_AUS_SA2.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA2/AUST/2016Census_G25_AUS_SA2.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA2/AUST/2016Census_G27_AUS_SA2.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA2/AUST/2016Census_G28_AUS_SA2.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA2/AUST/2016Census_G29_AUS_SA2.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA2/AUST/2016Census_G30_AUS_SA2.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA2/AUST/2016Census_G31_AUS_SA2.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA2/AUST/2016Census_G59_AUS_SA2.csv


./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA3/AUST/2016Census_G01_AUS_SA3.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA3/AUST/2016Census_G02_AUS_SA3.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA3/AUST/2016Census_G04A_AUS_SA3.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA3/AUST/2016Census_G04B_AUS_SA3.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA3/AUST/2016Census_G05_AUS_SA3.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA3/AUST/2016Census_G07_AUS_SA3.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA3/AUST/2016Census_G08_AUS_SA3.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA3/AUST/2016Census_G25_AUS_SA3.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA3/AUST/2016Census_G27_AUS_SA3.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA3/AUST/2016Census_G28_AUS_SA3.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA3/AUST/2016Census_G29_AUS_SA3.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA3/AUST/2016Census_G30_AUS_SA3.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA3/AUST/2016Census_G31_AUS_SA3.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA3/AUST/2016Census_G59_AUS_SA3.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA4/AUST/2016Census_G01_AUS_SA4.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA4/AUST/2016Census_G02_AUS_SA4.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA4/AUST/2016Census_G04A_AUS_SA4.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA4/AUST/2016Census_G04B_AUS_SA4.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA4/AUST/2016Census_G05_AUS_SA4.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA4/AUST/2016Census_G07_AUS_SA4.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA4/AUST/2016Census_G08_AUS_SA4.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA4/AUST/2016Census_G25_AUS_SA4.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA4/AUST/2016Census_G27_AUS_SA4.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA4/AUST/2016Census_G28_AUS_SA4.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA4/AUST/2016Census_G29_AUS_SA4.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA4/AUST/2016Census_G30_AUS_SA4.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA4/AUST/2016Census_G31_AUS_SA4.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SA4/AUST/2016Census_G59_AUS_SA4.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SED/AUST/2016Census_G01_AUS_SED.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SED/AUST/2016Census_G02_AUS_SED.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SED/AUST/2016Census_G04A_AUS_SED.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SED/AUST/2016Census_G04B_AUS_SED.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SED/AUST/2016Census_G05_AUS_SED.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SED/AUST/2016Census_G07_AUS_SED.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SED/AUST/2016Census_G08_AUS_SED.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SED/AUST/2016Census_G25_AUS_SED.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SED/AUST/2016Census_G27_AUS_SED.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SED/AUST/2016Census_G28_AUS_SED.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SED/AUST/2016Census_G29_AUS_SED.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SED/AUST/2016Census_G30_AUS_SED.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SED/AUST/2016Census_G31_AUS_SED.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SED/AUST/2016Census_G59_AUS_SED.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SOS/AUST/2016Census_G01_AUS_SOS.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SOS/AUST/2016Census_G02_AUS_SOS.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SOS/AUST/2016Census_G04A_AUS_SOS.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SOS/AUST/2016Census_G04B_AUS_SOS.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SOS/AUST/2016Census_G05_AUS_SOS.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SOS/AUST/2016Census_G07_AUS_SOS.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SOS/AUST/2016Census_G08_AUS_SOS.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SOS/AUST/2016Census_G25_AUS_SOS.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SOS/AUST/2016Census_G27_AUS_SOS.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SOS/AUST/2016Census_G28_AUS_SOS.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SOS/AUST/2016Census_G29_AUS_SOS.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SOS/AUST/2016Census_G30_AUS_SOS.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SOS/AUST/2016Census_G31_AUS_SOS.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SOS/AUST/2016Census_G59_AUS_SOS.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SOSR/AUST/2016Census_G01_AUS_SOSR.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SOSR/AUST/2016Census_G02_AUS_SOSR.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SOSR/AUST/2016Census_G04A_AUS_SOSR.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SOSR/AUST/2016Census_G04B_AUS_SOSR.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SOSR/AUST/2016Census_G05_AUS_SOSR.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SOSR/AUST/2016Census_G07_AUS_SOSR.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SOSR/AUST/2016Census_G08_AUS_SOSR.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SOSR/AUST/2016Census_G25_AUS_SOSR.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SOSR/AUST/2016Census_G27_AUS_SOSR.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SOSR/AUST/2016Census_G28_AUS_SOSR.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SOSR/AUST/2016Census_G29_AUS_SOSR.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SOSR/AUST/2016Census_G30_AUS_SOSR.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SOSR/AUST/2016Census_G31_AUS_SOSR.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SOSR/AUST/2016Census_G59_AUS_SOSR.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SSC/AUST/2016Census_G01_AUS_SSC.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SSC/AUST/2016Census_G02_AUS_SSC.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SSC/AUST/2016Census_G04A_AUS_SSC.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SSC/AUST/2016Census_G04B_AUS_SSC.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SSC/AUST/2016Census_G05_AUS_SSC.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SSC/AUST/2016Census_G07_AUS_SSC.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SSC/AUST/2016Census_G08_AUS_SSC.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SSC/AUST/2016Census_G25_AUS_SSC.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SSC/AUST/2016Census_G27_AUS_SSC.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SSC/AUST/2016Census_G28_AUS_SSC.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SSC/AUST/2016Census_G29_AUS_SSC.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SSC/AUST/2016Census_G30_AUS_SSC.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SSC/AUST/2016Census_G31_AUS_SSC.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SSC/AUST/2016Census_G59_AUS_SSC.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/STE/AUST/2016Census_G01_AUS_STE.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/STE/AUST/2016Census_G02_AUS_STE.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/STE/AUST/2016Census_G04A_AUS_STE.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/STE/AUST/2016Census_G04B_AUS_STE.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/STE/AUST/2016Census_G05_AUS_STE.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/STE/AUST/2016Census_G07_AUS_STE.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/STE/AUST/2016Census_G08_AUS_STE.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/STE/AUST/2016Census_G25_AUS_STE.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/STE/AUST/2016Census_G27_AUS_STE.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/STE/AUST/2016Census_G28_AUS_STE.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/STE/AUST/2016Census_G29_AUS_STE.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/STE/AUST/2016Census_G30_AUS_STE.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/STE/AUST/2016Census_G31_AUS_STE.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/STE/AUST/2016Census_G59_AUS_STE.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SUA/AUST/2016Census_G01_AUS_SUA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SUA/AUST/2016Census_G02_AUS_SUA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SUA/AUST/2016Census_G04A_AUS_SUA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SUA/AUST/2016Census_G04B_AUS_SUA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SUA/AUST/2016Census_G05_AUS_SUA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SUA/AUST/2016Census_G07_AUS_SUA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SUA/AUST/2016Census_G08_AUS_SUA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SUA/AUST/2016Census_G25_AUS_SUA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SUA/AUST/2016Census_G27_AUS_SUA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SUA/AUST/2016Census_G28_AUS_SUA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SUA/AUST/2016Census_G29_AUS_SUA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SUA/AUST/2016Census_G30_AUS_SUA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SUA/AUST/2016Census_G31_AUS_SUA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/SUA/AUST/2016Census_G59_AUS_SUA.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/UCL/AUST/2016Census_G01_AUS_UCL.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/UCL/AUST/2016Census_G02_AUS_UCL.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/UCL/AUST/2016Census_G04A_AUS_UCL.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/UCL/AUST/2016Census_G04B_AUS_UCL.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/UCL/AUST/2016Census_G05_AUS_UCL.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/UCL/AUST/2016Census_G07_AUS_UCL.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/UCL/AUST/2016Census_G08_AUS_UCL.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/UCL/AUST/2016Census_G25_AUS_UCL.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/UCL/AUST/2016Census_G27_AUS_UCL.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/UCL/AUST/2016Census_G28_AUS_UCL.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/UCL/AUST/2016Census_G29_AUS_UCL.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/UCL/AUST/2016Census_G30_AUS_UCL.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/UCL/AUST/2016Census_G31_AUS_UCL.csv
./csvtransform -c /home/gabe/Documents/census/2016_GCP_ALL_for_AUS_short-header/2016-Census-GCP-All-Geography-for-AUST/UCL/AUST/2016Census_G59_AUS_UCL.csv
