#!/bin/bash
# Note to self!
# Run this relative to the dbbuilder dir.
#
touch loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G01_AUS.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G01_AUS_GCCSA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G01_AUS_LGA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G01_AUS_POA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G01_AUS_RA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G01_AUS_SA2.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G02_AUS_SA3.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G01_AUS_SA4.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G01_AUS_SED.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G01_AUS_SOS.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G01_AUS_SOSR.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G01_AUS_SSC.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G01_AUS_STE.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G01_AUS_SUA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G01_AUS_UCL.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G02_AUS_CED.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G02_AUS.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G02_AUS_GCCSA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G02_AUS_LGA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G02_AUS_POA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G02_AUS_RA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G02_AUS_SA2.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G02_AUS_SA3.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G02_AUS_SA4.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G02_AUS_SED.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G02_AUS_SOS.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G02_AUS_SOSR.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G02_AUS_SSC.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G02_AUS_STE.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G02_AUS_SUA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G02_AUS_UCL.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04A_AUS_CED.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04A_AUS.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04A_AUS_GCCSA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04A_AUS_LGA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04A_AUS_POA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04A_AUS_RA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04A_AUS_SA2.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04A_AUS_SA3.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04A_AUS_SA4.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04A_AUS_SED.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04A_AUS_SOS.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04A_AUS_SOSR.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04A_AUS_SSC.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04A_AUS_STE.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04A_AUS_SUA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04A_AUS_UCL.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04B_AUS_CED.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04B_AUS.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04B_AUS_GCCSA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04B_AUS_LGA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04B_AUS_POA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04B_AUS_RA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04B_AUS_SA2.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04B_AUS_SA3.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04B_AUS_SA4.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04B_AUS_SED.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04B_AUS_SOS.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04B_AUS_SOSR.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04B_AUS_SSC.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04B_AUS_STE.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04B_AUS_SUA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G04B_AUS_UCL.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G05_AUS_CED.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G05_AUS.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G05_AUS_GCCSA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G05_AUS_LGA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G05_AUS_POA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G05_AUS_RA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G05_AUS_SA2.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G05_AUS_SA3.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G05_AUS_SA4.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G05_AUS_SED.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G05_AUS_SOS.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G05_AUS_SOSR.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G05_AUS_SSC.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G05_AUS_STE.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G05_AUS_SUA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G05_AUS_UCL.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G07_AUS_CED.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G07_AUS.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G07_AUS_GCCSA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G07_AUS_LGA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G07_AUS_POA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G07_AUS_RA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G07_AUS_SA2.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G07_AUS_SA3.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G07_AUS_SA4.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G07_AUS_SED.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G07_AUS_SOS.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G07_AUS_SOSR.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G07_AUS_SSC.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G07_AUS_STE.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G07_AUS_SUA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G07_AUS_UCL.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G08_AUS_CED.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G08_AUS.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G08_AUS_GCCSA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G08_AUS_LGA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G08_AUS_POA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G08_AUS_RA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G08_AUS_SA2.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G08_AUS_SA3.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G08_AUS_SA4.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G08_AUS_SED.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G08_AUS_SOS.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G08_AUS_SOSR.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G08_AUS_SSC.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G08_AUS_STE.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G08_AUS_SUA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G08_AUS_UCL.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G25_AUS_CED.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G25_AUS.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G25_AUS_GCCSA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G25_AUS_LGA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G25_AUS_POA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G25_AUS_RA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G25_AUS_SA2.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G25_AUS_SA3.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G25_AUS_SA4.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G25_AUS_SED.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G25_AUS_SOS.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G25_AUS_SOSR.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G25_AUS_SSC.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G25_AUS_STE.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G25_AUS_SUA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G25_AUS_UCL.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G27_AUS_CED.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G27_AUS.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G27_AUS_GCCSA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G27_AUS_LGA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G27_AUS_POA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G27_AUS_RA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G27_AUS_SA2.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G27_AUS_SA3.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G27_AUS_SA4.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G27_AUS_SED.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G27_AUS_SOS.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G27_AUS_SOSR.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G27_AUS_SSC.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G27_AUS_STE.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G27_AUS_SUA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G27_AUS_UCL.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G28_AUS_CED.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G28_AUS.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G28_AUS_GCCSA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G28_AUS_LGA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G28_AUS_POA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G28_AUS_RA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G28_AUS_SA2.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G28_AUS_SA3.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G28_AUS_SA4.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G28_AUS_SED.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G28_AUS_SOS.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G28_AUS_SOSR.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G28_AUS_SSC.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G28_AUS_STE.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G28_AUS_SUA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G28_AUS_UCL.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G29_AUS_CED.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G29_AUS.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G29_AUS_GCCSA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G29_AUS_LGA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G29_AUS_POA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G29_AUS_RA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G29_AUS_SA2.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G29_AUS_SA3.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G29_AUS_SA4.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G29_AUS_SED.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G29_AUS_SOS.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G29_AUS_SOSR.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G29_AUS_SSC.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G29_AUS_STE.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G29_AUS_SUA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G29_AUS_UCL.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G30_AUS_CED.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G30_AUS.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G30_AUS_GCCSA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G30_AUS_LGA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G30_AUS_POA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G30_AUS_RA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G30_AUS_SA2.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G30_AUS_SA3.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G30_AUS_SA4.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G30_AUS_SED.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G30_AUS_SOS.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G30_AUS_SOSR.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G30_AUS_SSC.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G30_AUS_STE.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G30_AUS_SUA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G30_AUS_UCL.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G31_AUS_CED.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G31_AUS.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G31_AUS_GCCSA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G31_AUS_LGA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G31_AUS_POA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G31_AUS_RA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G31_AUS_SA2.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G31_AUS_SA3.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G31_AUS_SA4.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G31_AUS_SED.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G31_AUS_SOS.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G31_AUS_SOSR.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G31_AUS_SSC.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G31_AUS_STE.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G31_AUS_SUA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G31_AUS_UCL.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G59_AUS_CED.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G59_AUS.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G59_AUS_GCCSA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G59_AUS_LGA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G59_AUS_POA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G59_AUS_RA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G59_AUS_SA2.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G59_AUS_SA3.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G59_AUS_SA4.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G59_AUS_SED.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G59_AUS_SOS.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G59_AUS_SOSR.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G59_AUS_SSC.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G59_AUS_STE.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G59_AUS_SUA.csv.json >> loadOutput.txt
./dbbuilder -n DPA_01 -l -f ../csvtransform/out_json/2016Census_G59_AUS_UCL.csv.json >> loadOutput.txt
