package main

// Yes I agree, this is bad. But meh This is too little and spares to put in the DB
// And not so big it can't be in memory. Something to re think in the future

//MetadataMapMap - a map of metadata maps.
var MetadataMapMap = map[string]map[string]string{
	"G01":  G01,
	"G02":  G02,
	"G04A": G04A,
	"G04B": G04B,
	"G05":  G05,
	"G07":  G07,
	"G08":  G08,
	"G25":  G25,
	"G27":  G27,
	"G28":  G28,
	"G29":  G29,
	"G30":  G30,
	"G31":  G31,
	"G59":  G59,
}

// G01 Selected Person Characteristics by Sex
var G01 = map[string]string{
	"Tot_P_M":                       "Total Persons Males",
	"Tot_P_F":                       "Total Persons Females",
	"Tot_P_P":                       "Total Persons Persons",
	"Age_0_4_yr_M":                  "Age groups 0 4 years Males",
	"Age_0_4_yr_F":                  "Age groups 0 4 years Females",
	"Age_0_4_yr_P":                  "Age groups 0 4 years Persons",
	"Age_5_14_yr_M":                 "Age groups 5 14 years Males",
	"Age_5_14_yr_F":                 "Age groups 5 14 years Females",
	"Age_5_14_yr_P":                 "Age groups 5 14 years Persons",
	"Age_15_19_yr_M":                "Age groups 15 19 years Males",
	"Age_15_19_yr_F":                "Age groups 15 19 years Females",
	"Age_15_19_yr_P":                "Age groups 15 19 years Persons",
	"Age_20_24_yr_M":                "Age groups 20 24 years Males",
	"Age_20_24_yr_F":                "Age groups 20 24 years Females",
	"Age_20_24_yr_P":                "Age groups 20 24 years Persons",
	"Age_25_34_yr_M":                "Age groups 25 34 years Males",
	"Age_25_34_yr_F":                "Age groups 25 34 years Females",
	"Age_25_34_yr_P":                "Age groups 25 34 years Persons",
	"Age_35_44_yr_M":                "Age groups 35 44 years Males",
	"Age_35_44_yr_F":                "Age groups 35 44 years Females",
	"Age_35_44_yr_P":                "Age groups 35 44 years Persons",
	"Age_45_54_yr_M":                "Age groups 45 54 years Males",
	"Age_45_54_yr_F":                "Age groups 45 54 years Females",
	"Age_45_54_yr_P":                "Age groups 45 54 years Persons",
	"Age_55_64_yr_M":                "Age groups 55 64 years Males",
	"Age_55_64_yr_F":                "Age groups 55 64 years Females",
	"Age_55_64_yr_P":                "Age groups 55 64 years Persons",
	"Age_65_74_yr_M":                "Age groups 65 74 years Males",
	"Age_65_74_yr_F":                "Age groups 65 74 years Females",
	"Age_65_74_yr_P":                "Age groups 65 74 years Persons",
	"Age_75_84_yr_M":                "Age groups 75 84 years Males",
	"Age_75_84_yr_F":                "Age groups 75 84 years Females",
	"Age_75_84_yr_P":                "Age groups 75 84 years Persons",
	"Age_85ov_M":                    "Age groups 85 years and over Males",
	"Age_85ov_F":                    "Age groups 85 years and over Females",
	"Age_85ov_P":                    "Age groups 85 years and over Persons",
	"Counted_Census_Night_home_M":   "Counted on Census Night At home Males",
	"Counted_Census_Night_home_F":   "Counted on Census Night At home Females",
	"Counted_Census_Night_home_P":   "Counted on Census Night At home Persons",
	"Count_Census_Nt_Ewhere_Aust_M": "Counted on Census Night Elsewhere in Australia Males",
	"Count_Census_Nt_Ewhere_Aust_F": "Counted on Census Night Elsewhere in Australia Females",
	"Count_Census_Nt_Ewhere_Aust_P": "Counted on Census Night Elsewhere in Australia Persons",
	"Indigenous_psns_Aboriginal_M":  "Aboriginal and or Torres Strait Islander Persons Aboriginal Males",
	"Indigenous_psns_Aboriginal_F":  "Aboriginal and or Torres Strait Islander Persons Aboriginal Females",
	"Indigenous_psns_Aboriginal_P":  "Aboriginal and or Torres Strait Islander Persons Aboriginal Persons",
	"Indig_psns_Torres_Strait_Is_M": "Aboriginal and or Torres Strait Islander Persons Torres Strait Islander Males",
	"Indig_psns_Torres_Strait_Is_F": "Aboriginal and or Torres Strait Islander Persons Torres Strait Islander Females",
	"Indig_psns_Torres_Strait_Is_P": "Aboriginal and or Torres Strait Islander Persons Torres Strait Islander Persons",
	"Indig_Bth_Abor_Torres_St_Is_M": "Aboriginal and or Torres Strait Islander Persons Both Aboriginal and Torres Strait Islander Males",
	"Indig_Bth_Abor_Torres_St_Is_F": "Aboriginal and or Torres Strait Islander Persons Both Aboriginal and Torres Strait Islander Females",
	"Indig_Bth_Abor_Torres_St_Is_P": "Aboriginal and or Torres Strait Islander Persons Both Aboriginal and Torres Strait Islander Persons",
	"Indigenous_P_Tot_M":            "Aboriginal and or Torres Strait Islander Persons Total Males",
	"Indigenous_P_Tot_F":            "Aboriginal and or Torres Strait Islander Persons Total Females",
	"Indigenous_P_Tot_P":            "Aboriginal and or Torres Strait Islander Persons Total Persons",
	"Birthplace_Australia_M":        "Birthplace Australia Males",
	"Birthplace_Australia_F":        "Birthplace Australia Females",
	"Birthplace_Australia_P":        "Birthplace Australia Persons",
	"Birthplace_Elsewhere_M":        "Birthplace Elsewhere Males",
	"Birthplace_Elsewhere_F":        "Birthplace Elsewhere Females",
	"Birthplace_Elsewhere_P":        "Birthplace Elsewhere Persons",
	"Lang_spoken_home_Eng_only_M":   "Language spoken at home English only Males",
	"Lang_spoken_home_Eng_only_F":   "Language spoken at home English only Females",
	"Lang_spoken_home_Eng_only_P":   "Language spoken at home English only Persons",
	"Lang_spoken_home_Oth_Lang_M":   "Language spoken at home Other Language Males",
	"Lang_spoken_home_Oth_Lang_F":   "Language spoken at home Other Language Females",
	"Lang_spoken_home_Oth_Lang_P":   "Language spoken at home Other Language Persons",
	"Australian_citizen_M":          "Australian citizen Males",
	"Australian_citizen_F":          "Australian citizen Females",
	"Australian_citizen_P":          "Australian citizen Persons",
	"Age_psns_att_educ_inst_0_4_M":  "Age of Persons attending an educational institution 0 4 years Males",
	"Age_psns_att_educ_inst_0_4_F":  "Age of Persons attending an educational institution 0 4 years Females",
	"Age_psns_att_educ_inst_0_4_P":  "Age of Persons attending an educational institution 0 4 years Persons",
	"Age_psns_att_educ_inst_5_14_M": "Age of Persons attending an educational institution 5 14 years Males",
	"Age_psns_att_educ_inst_5_14_F": "Age of Persons attending an educational institution 5 14 years Females",
	"Age_psns_att_educ_inst_5_14_P": "Age of Persons attending an educational institution 5 14 years Persons",
	"Age_psns_att_edu_inst_15_19_M": "Age of Persons attending an educational institution 15 19 years Males",
	"Age_psns_att_edu_inst_15_19_F": "Age of Persons attending an educational institution 15 19 years Females",
	"Age_psns_att_edu_inst_15_19_P": "Age of Persons attending an educational institution 15 19 years Persons",
	"Age_psns_att_edu_inst_20_24_M": "Age of Persons attending an educational institution 20 24 years Males",
	"Age_psns_att_edu_inst_20_24_F": "Age of Persons attending an educational institution 20 24 years Females",
	"Age_psns_att_edu_inst_20_24_P": "Age of Persons attending an educational institution 20 24 years Persons",
	"Age_psns_att_edu_inst_25_ov_M": "Age of Persons attending an educational institution 25 years and over Males",
	"Age_psns_att_edu_inst_25_ov_F": "Age of Persons attending an educational institution 25 years and over Females",
	"Age_psns_att_edu_inst_25_ov_P": "Age of Persons attending an educational institution 25 years and over Persons",
	"High_yr_schl_comp_Yr_12_eq_M":  "Highest year of school completed Year 12 or equivalent Males",
	"High_yr_schl_comp_Yr_12_eq_F":  "Highest year of school completed Year 12 or equivalent Females",
	"High_yr_schl_comp_Yr_12_eq_P":  "Highest year of school completed Year 12 or equivalent Persons",
	"High_yr_schl_comp_Yr_11_eq_M":  "Highest year of school completed Year 11 or equivalent Males",
	"High_yr_schl_comp_Yr_11_eq_F":  "Highest year of school completed Year 11 or equivalent Females",
	"High_yr_schl_comp_Yr_11_eq_P":  "Highest year of school completed Year 11 or equivalent Persons",
	"High_yr_schl_comp_Yr_10_eq_M":  "Highest year of school completed Year 10 or equivalent Males",
	"High_yr_schl_comp_Yr_10_eq_F":  "Highest year of school completed Year 10 or equivalent Females",
	"High_yr_schl_comp_Yr_10_eq_P":  "Highest year of school completed Year 10 or equivalent Persons",
	"High_yr_schl_comp_Yr_9_eq_M":   "Highest year of school completed Year 9 or equivalent Males",
	"High_yr_schl_comp_Yr_9_eq_F":   "Highest year of school completed Year 9 or equivalent Females",
	"High_yr_schl_comp_Yr_9_eq_P":   "Highest year of school completed Year 9 or equivalent Persons",
	"High_yr_schl_comp_Yr_8_belw_M": "Highest year of school completed Year 8 or below Males",
	"High_yr_schl_comp_Yr_8_belw_F": "Highest year of school completed Year 8 or below Females",
	"High_yr_schl_comp_Yr_8_belw_P": "Highest year of school completed Year 8 or below Persons",
	"High_yr_schl_comp_D_n_g_sch_M": "Highest year of school completed Did not go to school Males",
	"High_yr_schl_comp_D_n_g_sch_F": "Highest year of school completed Did not go to school Females",
	"High_yr_schl_comp_D_n_g_sch_P": "Highest year of school completed Did not go to school Persons",
	"Count_psns_occ_priv_dwgs_M":    "Count of Persons in occupied private dwellings Males",
	"Count_psns_occ_priv_dwgs_F":    "Count of Persons in occupied private dwellings Females",
	"Count_psns_occ_priv_dwgs_P":    "Count of Persons in occupied private dwellings Persons",
	"Count_Persons_other_dwgs_M":    "Count of Persons in other dwellings Males",
	"Count_Persons_other_dwgs_F":    "Count of Persons in other dwellings Females",
	"Count_Persons_other_dwgs_P":    "Count of Persons in other dwellings Persons",
}

//G02 Selected Medians and Averages
var G02 = map[string]string{
	"Median_age_persons":            "Median age of persons",
	"Median_mortgage_repay_monthly": "Median mortgage repayment monthly",
	"Median_tot_prsnl_inc_weekly":   "Median total personal income weekly",
	"Median_rent_weekly":            "Median rent weekly",
	"Median_tot_fam_inc_weekly":     "Median total family income weekly",
	"Average_num_psns_per_bedroom":  "Average number of Persons per bedroom",
	"Median_tot_hhd_inc_weekly":     "Median total household income weekly",
	"Average_household_size":        "Average household size",
}

//G04A Age by Sex
var G04A = map[string]string{
	"Age_yr_0_M":     "Age years 0 Males",
	"Age_yr_0_F":     "Age years 0 Females",
	"Age_yr_0_P":     "Age years 0 Persons",
	"Age_yr_1_M":     "Age years 1 Males",
	"Age_yr_1_F":     "Age years 1 Females",
	"Age_yr_1_P":     "Age years 1 Persons",
	"Age_yr_2_M":     "Age years 2 Males",
	"Age_yr_2_F":     "Age years 2 Females",
	"Age_yr_2_P":     "Age years 2 Persons",
	"Age_yr_3_M":     "Age years 3 Males",
	"Age_yr_3_F":     "Age years 3 Females",
	"Age_yr_3_P":     "Age years 3 Persons",
	"Age_yr_4_M":     "Age years 4 Males",
	"Age_yr_4_F":     "Age years 4 Females",
	"Age_yr_4_P":     "Age years 4 Persons",
	"Age_yr_0_4_M":   "Age years 0 4 years Males",
	"Age_yr_0_4_F":   "Age years 0 4 years Females",
	"Age_yr_0_4_P":   "Age years 0 4 years Persons",
	"Age_yr_5_M":     "Age years 5 Males",
	"Age_yr_5_F":     "Age years 5 Females",
	"Age_yr_5_P":     "Age years 5 Persons",
	"Age_yr_6_M":     "Age years 6 Males",
	"Age_yr_6_F":     "Age years 6 Females",
	"Age_yr_6_P":     "Age years 6 Persons",
	"Age_yr_7_M":     "Age years 7 Males",
	"Age_yr_7_F":     "Age years 7 Females",
	"Age_yr_7_P":     "Age years 7 Persons",
	"Age_yr_8_M":     "Age years 8 Males",
	"Age_yr_8_F":     "Age years 8 Females",
	"Age_yr_8_P":     "Age years 8 Persons",
	"Age_yr_9_M":     "Age years 9 Males",
	"Age_yr_9_F":     "Age years 9 Females",
	"Age_yr_9_P":     "Age years 9 Persons",
	"Age_yr_5_9_M":   "Age years 5 9 years Males",
	"Age_yr_5_9_F":   "Age years 5 9 years Females",
	"Age_yr_5_9_P":   "Age years 5 9 years Persons",
	"Age_yr_10_M":    "Age years 10 Males",
	"Age_yr_10_F":    "Age years 10 Females",
	"Age_yr_10_P":    "Age years 10 Persons",
	"Age_yr_11_M":    "Age years 11 Males",
	"Age_yr_11_F":    "Age years 11 Females",
	"Age_yr_11_P":    "Age years 11 Persons",
	"Age_yr_12_M":    "Age years 12 Males",
	"Age_yr_12_F":    "Age years 12 Females",
	"Age_yr_12_P":    "Age years 12 Persons",
	"Age_yr_13_M":    "Age years 13 Males",
	"Age_yr_13_F":    "Age years 13 Females",
	"Age_yr_13_P":    "Age years 13 Persons",
	"Age_yr_14_M":    "Age years 14 Males",
	"Age_yr_14_F":    "Age years 14 Females",
	"Age_yr_14_P":    "Age years 14 Persons",
	"Age_yr_10_14_M": "Age years 10 14 years Males",
	"Age_yr_10_14_F": "Age years 10 14 years Females",
	"Age_yr_10_14_P": "Age years 10 14 years Persons",
	"Age_yr_15_M":    "Age years 15 Males",
	"Age_yr_15_F":    "Age years 15 Females",
	"Age_yr_15_P":    "Age years 15 Persons",
	"Age_yr_16_M":    "Age years 16 Males",
	"Age_yr_16_F":    "Age years 16 Females",
	"Age_yr_16_P":    "Age years 16 Persons",
	"Age_yr_17_M":    "Age years 17 Males",
	"Age_yr_17_F":    "Age years 17 Females",
	"Age_yr_17_P":    "Age years 17 Persons",
	"Age_yr_18_M":    "Age years 18 Males",
	"Age_yr_18_F":    "Age years 18 Females",
	"Age_yr_18_P":    "Age years 18 Persons",
	"Age_yr_19_M":    "Age years 19 Males",
	"Age_yr_19_F":    "Age years 19 Females",
	"Age_yr_19_P":    "Age years 19 Persons",
	"Age_yr_15_19_M": "Age years 15 19 years Males",
	"Age_yr_15_19_F": "Age years 15 19 years Females",
	"Age_yr_15_19_P": "Age years 15 19 years Persons",
	"Age_yr_20_M":    "Age years 20 Males",
	"Age_yr_20_F":    "Age years 20 Females",
	"Age_yr_20_P":    "Age years 20 Persons",
	"Age_yr_21_M":    "Age years 21 Males",
	"Age_yr_21_F":    "Age years 21 Females",
	"Age_yr_21_P":    "Age years 21 Persons",
	"Age_yr_22_M":    "Age years 22 Males",
	"Age_yr_22_F":    "Age years 22 Females",
	"Age_yr_22_P":    "Age years 22 Persons",
	"Age_yr_23_M":    "Age years 23 Males",
	"Age_yr_23_F":    "Age years 23 Females",
	"Age_yr_23_P":    "Age years 23 Persons",
	"Age_yr_24_M":    "Age years 24 Males",
	"Age_yr_24_F":    "Age years 24 Females",
	"Age_yr_24_P":    "Age years 24 Persons",
	"Age_yr_20_24_M": "Age years 20 24 years Males",
	"Age_yr_20_24_F": "Age years 20 24 years Females",
	"Age_yr_20_24_P": "Age years 20 24 years Persons",
	"Age_yr_25_M":    "Age years 25 Males",
	"Age_yr_25_F":    "Age years 25 Females",
	"Age_yr_25_P":    "Age years 25 Persons",
	"Age_yr_26_M":    "Age years 26 Males",
	"Age_yr_26_F":    "Age years 26 Females",
	"Age_yr_26_P":    "Age years 26 Persons",
	"Age_yr_27_M":    "Age years 27 Males",
	"Age_yr_27_F":    "Age years 27 Females",
	"Age_yr_27_P":    "Age years 27 Persons",
	"Age_yr_28_M":    "Age years 28 Males",
	"Age_yr_28_F":    "Age years 28 Females",
	"Age_yr_28_P":    "Age years 28 Persons",
	"Age_yr_29_M":    "Age years 29 Males",
	"Age_yr_29_F":    "Age years 29 Females",
	"Age_yr_29_P":    "Age years 29 Persons",
	"Age_yr_25_29_M": "Age years 25 29 years Males",
	"Age_yr_25_29_F": "Age years 25 29 years Females",
	"Age_yr_25_29_P": "Age years 25 29 years Persons",
	"Age_yr_30_M":    "Age years 30 Males",
	"Age_yr_30_F":    "Age years 30 Females",
	"Age_yr_30_P":    "Age years 30 Persons",
	"Age_yr_31_M":    "Age years 31 Males",
	"Age_yr_31_F":    "Age years 31 Females",
	"Age_yr_31_P":    "Age years 31 Persons",
	"Age_yr_32_M":    "Age years 32 Males",
	"Age_yr_32_F":    "Age years 32 Females",
	"Age_yr_32_P":    "Age years 32 Persons",
	"Age_yr_33_M":    "Age years 33 Males",
	"Age_yr_33_F":    "Age years 33 Females",
	"Age_yr_33_P":    "Age years 33 Persons",
	"Age_yr_34_M":    "Age years 34 Males",
	"Age_yr_34_F":    "Age years 34 Females",
	"Age_yr_34_P":    "Age years 34 Persons",
	"Age_yr_30_34_M": "Age years 30 34 years Males",
	"Age_yr_30_34_F": "Age years 30 34 years Females",
	"Age_yr_30_34_P": "Age years 30 34 years Persons",
	"Age_yr_35_M":    "Age years 35 Males",
	"Age_yr_35_F":    "Age years 35 Females",
	"Age_yr_35_P":    "Age years 35 Persons",
	"Age_yr_36_M":    "Age years 36 Males",
	"Age_yr_36_F":    "Age years 36 Females",
	"Age_yr_36_P":    "Age years 36 Persons",
	"Age_yr_37_M":    "Age years 37 Males",
	"Age_yr_37_F":    "Age years 37 Females",
	"Age_yr_37_P":    "Age years 37 Persons",
	"Age_yr_38_M":    "Age years 38 Males",
	"Age_yr_38_F":    "Age years 38 Females",
	"Age_yr_38_P":    "Age years 38 Persons",
	"Age_yr_39_M":    "Age years 39 Males",
	"Age_yr_39_F":    "Age years 39 Females",
	"Age_yr_39_P":    "Age years 39 Persons",
	"Age_yr_35_39_M": "Age years 35 39 years Males",
	"Age_yr_35_39_F": "Age years 35 39 years Females",
	"Age_yr_35_39_P": "Age years 35 39 years Persons",
	"Age_yr_40_M":    "Age years 40 Males",
	"Age_yr_40_F":    "Age years 40 Females",
	"Age_yr_40_P":    "Age years 40 Persons",
	"Age_yr_41_M":    "Age years 41 Males",
	"Age_yr_41_F":    "Age years 41 Females",
	"Age_yr_41_P":    "Age years 41 Persons",
	"Age_yr_42_M":    "Age years 42 Males",
	"Age_yr_42_F":    "Age years 42 Females",
	"Age_yr_42_P":    "Age years 42 Persons",
	"Age_yr_43_M":    "Age years 43 Males",
	"Age_yr_43_F":    "Age years 43 Females",
	"Age_yr_43_P":    "Age years 43 Persons",
	"Age_yr_44_M":    "Age years 44 Males",
	"Age_yr_44_F":    "Age years 44 Females",
	"Age_yr_44_P":    "Age years 44 Persons",
	"Age_yr_40_44_M": "Age years 40 44 years Males",
	"Age_yr_40_44_F": "Age years 40 44 years Females",
	"Age_yr_40_44_P": "Age years 40 44 years Persons",
	"Age_yr_45_M":    "Age years 45 Males",
	"Age_yr_45_F":    "Age years 45 Females",
	"Age_yr_45_P":    "Age years 45 Persons",
	"Age_yr_46_M":    "Age years 46 Males",
	"Age_yr_46_F":    "Age years 46 Females",
	"Age_yr_46_P":    "Age years 46 Persons",
	"Age_yr_47_M":    "Age years 47 Males",
	"Age_yr_47_F":    "Age years 47 Females",
	"Age_yr_47_P":    "Age years 47 Persons",
	"Age_yr_48_M":    "Age years 48 Males",
	"Age_yr_48_F":    "Age years 48 Females",
	"Age_yr_48_P":    "Age years 48 Persons",
	"Age_yr_49_M":    "Age years 49 Males",
	"Age_yr_49_F":    "Age years 49 Females",
	"Age_yr_49_P":    "Age years 49 Persons",
	"Age_yr_45_49_M": "Age years 45 49 years Males",
	"Age_yr_45_49_F": "Age years 45 49 years Females",
	"Age_yr_45_49_P": "Age years 45 49 years Persons",
	"Age_yr_50_M":    "Age years 50 Males",
	"Age_yr_50_F":    "Age years 50 Females",
	"Age_yr_50_P":    "Age years 50 Persons",
	"Age_yr_51_M":    "Age years 51 Males",
	"Age_yr_51_F":    "Age years 51 Females",
	"Age_yr_51_P":    "Age years 51 Persons",
	"Age_yr_52_M":    "Age years 52 Males",
	"Age_yr_52_F":    "Age years 52 Females",
	"Age_yr_52_P":    "Age years 52 Persons",
	"Age_yr_53_M":    "Age years 53 Males",
	"Age_yr_53_F":    "Age years 53 Females",
	"Age_yr_53_P":    "Age years 53 Persons",
	"Age_yr_54_M":    "Age years 54 Males",
	"Age_yr_54_F":    "Age years 54 Females",
	"Age_yr_54_P":    "Age years 54 Persons",
	"Age_yr_50_54_M": "Age years 50 54 years Males",
	"Age_yr_50_54_F": "Age years 50 54 years Females",
	"Age_yr_50_54_P": "Age years 50 54 years Persons",
	"Age_yr_55_M":    "Age years 55 Males",
	"Age_yr_55_F":    "Age years 55 Females",
}

//G04B Age by Sex
var G04B = map[string]string{
	"Age_yr_55_P":          "Age years 55 Persons",
	"Age_yr_56_M":          "Age years 56 Males",
	"Age_yr_56_F":          "Age years 56 Females",
	"Age_yr_56_P":          "Age years 56 Persons",
	"Age_yr_57_M":          "Age years 57 Males",
	"Age_yr_57_F":          "Age years 57 Females",
	"Age_yr_57_P":          "Age years 57 Persons",
	"Age_yr_58_M":          "Age years 58 Males",
	"Age_yr_58_F":          "Age years 58 Females",
	"Age_yr_58_P":          "Age years 58 Persons",
	"Age_yr_59_M":          "Age years 59 Males",
	"Age_yr_59_F":          "Age years 59 Females",
	"Age_yr_59_P":          "Age years 59 Persons",
	"Age_yr_55_59_M":       "Age years 55 59 years Males",
	"Age_yr_55_59_F":       "Age years 55 59 years Females",
	"Age_yr_55_59_P":       "Age years 55 59 years Persons",
	"Age_yr_60_M":          "Age years 60 Males",
	"Age_yr_60_F":          "Age years 60 Females",
	"Age_yr_60_P":          "Age years 60 Persons",
	"Age_yr_61_M":          "Age years 61 Males",
	"Age_yr_61_F":          "Age years 61 Females",
	"Age_yr_61_P":          "Age years 61 Persons",
	"Age_yr_62_M":          "Age years 62 Males",
	"Age_yr_62_F":          "Age years 62 Females",
	"Age_yr_62_P":          "Age years 62 Persons",
	"Age_yr_63_M":          "Age years 63 Males",
	"Age_yr_63_F":          "Age years 63 Females",
	"Age_yr_63_P":          "Age years 63 Persons",
	"Age_yr_64_M":          "Age years 64 Males",
	"Age_yr_64_F":          "Age years 64 Females",
	"Age_yr_64_P":          "Age years 64 Persons",
	"Age_yr_60_64_M":       "Age years 60 64 years Males",
	"Age_yr_60_64_F":       "Age years 60 64 years Females",
	"Age_yr_60_64_P":       "Age years 60 64 years Persons",
	"Age_yr_65_M":          "Age years 65 Males",
	"Age_yr_65_F":          "Age years 65 Females",
	"Age_yr_65_P":          "Age years 65 Persons",
	"Age_yr_66_M":          "Age years 66 Males",
	"Age_yr_66_F":          "Age years 66 Females",
	"Age_yr_66_P":          "Age years 66 Persons",
	"Age_yr_67_M":          "Age years 67 Males",
	"Age_yr_67_F":          "Age years 67 Females",
	"Age_yr_67_P":          "Age years 67 Persons",
	"Age_yr_68_M":          "Age years 68 Males",
	"Age_yr_68_F":          "Age years 68 Females",
	"Age_yr_68_P":          "Age years 68 Persons",
	"Age_yr_69_M":          "Age years 69 Males",
	"Age_yr_69_F":          "Age years 69 Females",
	"Age_yr_69_P":          "Age years 69 Persons",
	"Age_yr_65_69_M":       "Age years 65 69 years Males",
	"Age_yr_65_69_F":       "Age years 65 69 years Females",
	"Age_yr_65_69_P":       "Age years 65 69 years Persons",
	"Age_yr_70_M":          "Age years 70 Males",
	"Age_yr_70_F":          "Age years 70 Females",
	"Age_yr_70_P":          "Age years 70 Persons",
	"Age_yr_71_M":          "Age years 71 Males",
	"Age_yr_71_F":          "Age years 71 Females",
	"Age_yr_71_P":          "Age years 71 Persons",
	"Age_yr_72_M":          "Age years 72 Males",
	"Age_yr_72_F":          "Age years 72 Females",
	"Age_yr_72_P":          "Age years 72 Persons",
	"Age_yr_73_M":          "Age years 73 Males",
	"Age_yr_73_F":          "Age years 73 Females",
	"Age_yr_73_P":          "Age years 73 Persons",
	"Age_yr_74_M":          "Age years 74 Males",
	"Age_yr_74_F":          "Age years 74 Females",
	"Age_yr_74_P":          "Age years 74 Persons",
	"Age_yr_70_74_M":       "Age years 70 74 years Males",
	"Age_yr_70_74_F":       "Age years 70 74 years Females",
	"Age_yr_70_74_P":       "Age years 70 74 years Persons",
	"Age_yr_75_M":          "Age years 75 Males",
	"Age_yr_75_F":          "Age years 75 Females",
	"Age_yr_75_P":          "Age years 75 Persons",
	"Age_yr_76_M":          "Age years 76 Males",
	"Age_yr_76_F":          "Age years 76 Females",
	"Age_yr_76_P":          "Age years 76 Persons",
	"Age_yr_77_M":          "Age years 77 Males",
	"Age_yr_77_F":          "Age years 77 Females",
	"Age_yr_77_P":          "Age years 77 Persons",
	"Age_yr_78_M":          "Age years 78 Males",
	"Age_yr_78_F":          "Age years 78 Females",
	"Age_yr_78_P":          "Age years 78 Persons",
	"Age_yr_79_M":          "Age years 79 Males",
	"Age_yr_79_F":          "Age years 79 Females",
	"Age_yr_79_P":          "Age years 79 Persons",
	"Age_yr_75_79_M":       "Age years 75 79 years Males",
	"Age_yr_75_79_F":       "Age years 75 79 years Females",
	"Age_yr_75_79_P":       "Age years 75 79 years Persons",
	"Age_yr_80_84_M":       "Age years 80 84 years Males",
	"Age_yr_80_84_F":       "Age years 80 84 years Females",
	"Age_yr_80_84_P":       "Age years 80 84 years Persons",
	"Age_yr_85_89_M":       "Age years 85 89 years Males",
	"Age_yr_85_89_F":       "Age years 85 89 years Females",
	"Age_yr_85_89_P":       "Age years 85 89 years Persons",
	"Age_yr_90_94_M":       "Age years 90 94 years Males",
	"Age_yr_90_94_F":       "Age years 90 94 years Females",
	"Age_yr_90_94_P":       "Age years 90 94 years Persons",
	"Age_yr_95_99_M":       "Age years 95 99 years Males",
	"Age_yr_95_99_F":       "Age years 95 99 years Females",
	"Age_yr_95_99_P":       "Age years 95 99 years Persons",
	"Age_yr_100_yr_over_M": "Age years 100 years and over Males",
	"Age_yr_100_yr_over_F": "Age years 100 years and over Females",
	"Age_yr_100_yr_over_P": "Age years 100 years and over Persons",
	"Tot_M":                "Total Males",
	"Tot_F":                "Total Females",
	"Tot_P":                "Total Persons",
}

//G05 Registered Marital Status by Age by Sex
var G05 = map[string]string{
	"M_15_19_yr_Married":       "Males 15 19 years Married",
	"M_15_19_yr_Separated":     "Males 15 19 years Separated",
	"M_15_19_yr_Divorced":      "Males 15 19 years Divorced",
	"M_15_19_yr_Widowed":       "Males 15 19 years Widowed",
	"M_15_19_yr_Never_Married": "Males 15 19 years Never Married",
	"M_15_19_yr_Tot":           "Males 15 19 years Total",
	"M_20_24_yr_Married":       "Males 20 24 years Married",
	"M_20_24_yr_Separated":     "Males 20 24 years Separated",
	"M_20_24_yr_Divorced":      "Males 20 24 years Divorced",
	"M_20_24_yr_Widowed":       "Males 20 24 years Widowed",
	"M_20_24_yr_Never_Married": "Males 20 24 years Never Married",
	"M_20_24_yr_Tot":           "Males 20 24 years Total",
	"M_25_34_yr_Married":       "Males 25 34 years Married",
	"M_25_34_yr_Separated":     "Males 25 34 years Separated",
	"M_25_34_yr_Divorced":      "Males 25 34 years Divorced",
	"M_25_34_yr_Widowed":       "Males 25 34 years Widowed",
	"M_25_34_yr_Never_Married": "Males 25 34 years Never Married",
	"M_25_34_yr_Tot":           "Males 25 34 years Total",
	"M_35_44_yr_Married":       "Males 35 44 years Married",
	"M_35_44_yr_Separated":     "Males 35 44 years Separated",
	"M_35_44_yr_Divorced":      "Males 35 44 years Divorced",
	"M_35_44_yr_Widowed":       "Males 35 44 years Widowed",
	"M_35_44_yr_Never_Married": "Males 35 44 years Never Married",
	"M_35_44_yr_Tot":           "Males 35 44 years Total",
	"M_45_54_yr_Married":       "Males 45 54 years Married",
	"M_45_54_yr_Separated":     "Males 45 54 years Separated",
	"M_45_54_yr_Divorced":      "Males 45 54 years Divorced",
	"M_45_54_yr_Widowed":       "Males 45 54 years Widowed",
	"M_45_54_yr_Never_Married": "Males 45 54 years Never Married",
	"M_45_54_yr_Tot":           "Males 45 54 years Total",
	"M_55_64_yr_Married":       "Males 55 64 years Married",
	"M_55_64_yr_Separated":     "Males 55 64 years Separated",
	"M_55_64_yr_Divorced":      "Males 55 64 years Divorced",
	"M_55_64_yr_Widowed":       "Males 55 64 years Widowed",
	"M_55_64_yr_Never_Married": "Males 55 64 years Never Married",
	"M_55_64_yr_Tot":           "Males 55 64 years Total",
	"M_65_74_yr_Married":       "Males 65 74 years Married",
	"M_65_74_yr_Separated":     "Males 65 74 years Separated",
	"M_65_74_yr_Divorced":      "Males 65 74 years Divorced",
	"M_65_74_yr_Widowed":       "Males 65 74 years Widowed",
	"M_65_74_yr_Never_Married": "Males 65 74 years Never Married",
	"M_65_74_yr_Tot":           "Males 65 74 years Total",
	"M_75_84_yr_Married":       "Males 75 84 years Married",
	"M_75_84_yr_Separated":     "Males 75 84 years Separated",
	"M_75_84_yr_Divorced":      "Males 75 84 years Divorced",
	"M_75_84_yr_Widowed":       "Males 75 84 years Widowed",
	"M_75_84_yr_Never_Married": "Males 75 84 years Never Married",
	"M_75_84_yr_Tot":           "Males 75 84 years Total",
	"M_85ov_Married":           "Males 85 years and over Married",
	"M_85ov_Separated":         "Males 85 years and over Separated",
	"M_85ov_Divorced":          "Males 85 years and over Divorced",
	"M_85ov_Widowed":           "Males 85 years and over Widowed",
	"M_85ov_Never_Married":     "Males 85 years and over Never Married",
	"M_85ov_Tot":               "Males 85 years and over Total",
	"M_Tot_Married":            "Males Total Married",
	"M_Tot_Separated":          "Males Total Separated",
	"M_Tot_Divorced":           "Males Total Divorced",
	"M_Tot_Widowed":            "Males Total Widowed",
	"M_Tot_Never_Married":      "Males Total Never Married",
	"M_Tot_Tot":                "Males Total Total",
	"F_15_19_yr_Married":       "Females 15 19 years Married",
	"F_15_19_yr_Separated":     "Females 15 19 years Separated",
	"F_15_19_yr_Divorced":      "Females 15 19 years Divorced",
	"F_15_19_yr_Widowed":       "Females 15 19 years Widowed",
	"F_15_19_yr_Never_Married": "Females 15 19 years Never Married",
	"F_15_19_yr_Tot":           "Females 15 19 years Total",
	"F_20_24_yr_Married":       "Females 20 24 years Married",
	"F_20_24_yr_Separated":     "Females 20 24 years Separated",
	"F_20_24_yr_Divorced":      "Females 20 24 years Divorced",
	"F_20_24_yr_Widowed":       "Females 20 24 years Widowed",
	"F_20_24_yr_Never_Married": "Females 20 24 years Never Married",
	"F_20_24_yr_Tot":           "Females 20 24 years Total",
	"F_25_34_yr_Married":       "Females 25 34 years Married",
	"F_25_34_yr_Separated":     "Females 25 34 years Separated",
	"F_25_34_yr_Divorced":      "Females 25 34 years Divorced",
	"F_25_34_yr_Widowed":       "Females 25 34 years Widowed",
	"F_25_34_yr_Never_Married": "Females 25 34 years Never Married",
	"F_25_34_yr_Tot":           "Females 25 34 years Total",
	"F_35_44_yr_Married":       "Females 35 44 years Married",
	"F_35_44_yr_Separated":     "Females 35 44 years Separated",
	"F_35_44_yr_Divorced":      "Females 35 44 years Divorced",
	"F_35_44_yr_Widowed":       "Females 35 44 years Widowed",
	"F_35_44_yr_Never_Married": "Females 35 44 years Never Married",
	"F_35_44_yr_Tot":           "Females 35 44 years Total",
	"F_45_54_yr_Married":       "Females 45 54 years Married",
	"F_45_54_yr_Separated":     "Females 45 54 years Separated",
	"F_45_54_yr_Divorced":      "Females 45 54 years Divorced",
	"F_45_54_yr_Widowed":       "Females 45 54 years Widowed",
	"F_45_54_yr_Never_Married": "Females 45 54 years Never Married",
	"F_45_54_yr_Tot":           "Females 45 54 years Total",
	"F_55_64_yr_Married":       "Females 55 64 years Married",
	"F_55_64_yr_Separated":     "Females 55 64 years Separated",
	"F_55_64_yr_Divorced":      "Females 55 64 years Divorced",
	"F_55_64_yr_Widowed":       "Females 55 64 years Widowed",
	"F_55_64_yr_Never_Married": "Females 55 64 years Never Married",
	"F_55_64_yr_Tot":           "Females 55 64 years Total",
	"F_65_74_yr_Married":       "Females 65 74 years Married",
	"F_65_74_yr_Separated":     "Females 65 74 years Separated",
	"F_65_74_yr_Divorced":      "Females 65 74 years Divorced",
	"F_65_74_yr_Widowed":       "Females 65 74 years Widowed",
	"F_65_74_yr_Never_Married": "Females 65 74 years Never Married",
	"F_65_74_yr_Tot":           "Females 65 74 years Total",
	"F_75_84_yr_Married":       "Females 75 84 years Married",
	"F_75_84_yr_Separated":     "Females 75 84 years Separated",
	"F_75_84_yr_Divorced":      "Females 75 84 years Divorced",
	"F_75_84_yr_Widowed":       "Females 75 84 years Widowed",
	"F_75_84_yr_Never_Married": "Females 75 84 years Never Married",
	"F_75_84_yr_Tot":           "Females 75 84 years Total",
	"F_85ov_Married":           "Females 85 years and over Married",
	"F_85ov_Separated":         "Females 85 years and over Separated",
	"F_85ov_Divorced":          "Females 85 years and over Divorced",
	"F_85ov_Widowed":           "Females 85 years and over Widowed",
	"F_85ov_Never_Married":     "Females 85 years and over Never Married",
	"F_85ov_Tot":               "Females 85 years and over Total",
	"F_Tot_Married":            "Females Total Married",
	"F_Tot_Separated":          "Females Total Separated",
	"F_Tot_Divorced":           "Females Total Divorced",
	"F_Tot_Widowed":            "Females Total Widowed",
	"F_Tot_Never_Married":      "Females Total Never Married",
	"F_Tot_Tot":                "Females Total Total",
	"P_15_19_yr_Married":       "Persons 15 19 years Married",
	"P_15_19_yr_Separated":     "Persons 15 19 years Separated",
	"P_15_19_yr_Divorced":      "Persons 15 19 years Divorced",
	"P_15_19_yr_Widowed":       "Persons 15 19 years Widowed",
	"P_15_19_yr_Never_Married": "Persons 15 19 years Never Married",
	"P_15_19_yr_Tot":           "Persons 15 19 years Total",
	"P_20_24_yr_Married":       "Persons 20 24 years Married",
	"P_20_24_yr_Separated":     "Persons 20 24 years Separated",
	"P_20_24_yr_Divorced":      "Persons 20 24 years Divorced",
	"P_20_24_yr_Widowed":       "Persons 20 24 years Widowed",
	"P_20_24_yr_Never_Married": "Persons 20 24 years Never Married",
	"P_20_24_yr_Tot":           "Persons 20 24 years Total",
	"P_25_34_yr_Married":       "Persons 25 34 years Married",
	"P_25_34_yr_Separated":     "Persons 25 34 years Separated",
	"P_25_34_yr_Divorced":      "Persons 25 34 years Divorced",
	"P_25_34_yr_Widowed":       "Persons 25 34 years Widowed",
	"P_25_34_yr_Never_Married": "Persons 25 34 years Never Married",
	"P_25_34_yr_Tot":           "Persons 25 34 years Total",
	"P_35_44_yr_Married":       "Persons 35 44 years Married",
	"P_35_44_yr_Separated":     "Persons 35 44 years Separated",
	"P_35_44_yr_Divorced":      "Persons 35 44 years Divorced",
	"P_35_44_yr_Widowed":       "Persons 35 44 years Widowed",
	"P_35_44_yr_Never_Married": "Persons 35 44 years Never Married",
	"P_35_44_yr_Tot":           "Persons 35 44 years Total",
	"P_45_54_yr_Married":       "Persons 45 54 years Married",
	"P_45_54_yr_Separated":     "Persons 45 54 years Separated",
	"P_45_54_yr_Divorced":      "Persons 45 54 years Divorced",
	"P_45_54_yr_Widowed":       "Persons 45 54 years Widowed",
	"P_45_54_yr_Never_Married": "Persons 45 54 years Never Married",
	"P_45_54_yr_Tot":           "Persons 45 54 years Total",
	"P_55_64_yr_Married":       "Persons 55 64 years Married",
	"P_55_64_yr_Separated":     "Persons 55 64 years Separated",
	"P_55_64_yr_Divorced":      "Persons 55 64 years Divorced",
	"P_55_64_yr_Widowed":       "Persons 55 64 years Widowed",
	"P_55_64_yr_Never_Married": "Persons 55 64 years Never Married",
	"P_55_64_yr_Tot":           "Persons 55 64 years Total",
	"P_65_74_yr_Married":       "Persons 65 74 years Married",
	"P_65_74_yr_Separated":     "Persons 65 74 years Separated",
	"P_65_74_yr_Divorced":      "Persons 65 74 years Divorced",
	"P_65_74_yr_Widowed":       "Persons 65 74 years Widowed",
	"P_65_74_yr_Never_Married": "Persons 65 74 years Never Married",
	"P_65_74_yr_Tot":           "Persons 65 74 years Total",
	"P_75_84_yr_Married":       "Persons 75 84 years Married",
	"P_75_84_yr_Separated":     "Persons 75 84 years Separated",
	"P_75_84_yr_Divorced":      "Persons 75 84 years Divorced",
	"P_75_84_yr_Widowed":       "Persons 75 84 years Widowed",
	"P_75_84_yr_Never_Married": "Persons 75 84 years Never Married",
	"P_75_84_yr_Tot":           "Persons 75 84 years Total",
	"P_85ov_Married":           "Persons 85 years and over Married",
	"P_85ov_Separated":         "Persons 85 years and over Separated",
	"P_85ov_Divorced":          "Persons 85 years and over Divorced",
	"P_85ov_Widowed":           "Persons 85 years and over Widowed",
	"P_85ov_Never_Married":     "Persons 85 years and over Never Married",
	"P_85ov_Tot":               "Persons 85 years and over Total",
	"P_Tot_Married":            "Persons Total Married",
	"P_Tot_Separated":          "Persons Total Separated",
	"P_Tot_Divorced":           "Persons Total Divorced",
	"P_Tot_Widowed":            "Persons Total Widowed",
	"P_Tot_Never_Married":      "Persons Total Never Married",
	"P_Tot_Tot":                "Persons Total Total",
}

//G07 Indigenous Status by Age by Sex
var G07 = map[string]string{
	"A_0_4_y_Indigenous_M":      "0 4 years Aboriginal and or Torres Strait Islander Males",
	"A_0_4_y_Indigenous_F":      "0 4 years Aboriginal and or Torres Strait Islander Females",
	"A_0_4_y_Indigenous_P":      "0 4 years Aboriginal and or Torres Strait Islander Persons",
	"A_0_4_y_Non_Indigenous_M":  "0 4 years Non Indigenous Males",
	"A_0_4_y_Non_Indigenous_F":  "0 4 years Non Indigenous Females",
	"A_0_4_y_Non_Indigenous_P":  "0 4 years Non Indigenous Persons",
	"A_0_4_y_Indig_stat_ns_M":   "0 4 years Indigenous status not stated Males",
	"A_0_4_y_Indig_stat_ns_F":   "0 4 years Indigenous status not stated Females",
	"A_0_4_y_Indig_stat_ns_P":   "0 4 years Indigenous status not stated Persons",
	"A_0_4_y_Tot_M":             "0 4 years Total Males",
	"A_0_4_y_Tot_F":             "0 4 years Total Females",
	"A_0_4_y_Tot_P":             "0 4 years Total Persons",
	"A_5_9_y_Indigenous_M":      "5 9 years Aboriginal and or Torres Strait Islander Males",
	"A_5_9_y_Indigenous_F":      "5 9 years Aboriginal and or Torres Strait Islander Females",
	"A_5_9_y_Indigenous_P":      "5 9 years Aboriginal and or Torres Strait Islander Persons",
	"A_5_9_y_Non_Indigenous_M":  "5 9 years Non Indigenous Males",
	"A_5_9_y_Non_Indigenous_F":  "5 9 years Non Indigenous Females",
	"A_5_9_y_Non_Indigenous_P":  "5 9 years Non Indigenous Persons",
	"A_5_9_y_Indig_stat_ns_M":   "5 9 years Indigenous status not stated Males",
	"A_5_9_y_Indig_stat_ns_F":   "5 9 years Indigenous status not stated Females",
	"A_5_9_y_Indig_stat_ns_P":   "5 9 years Indigenous status not stated Persons",
	"A_5_9_y_Tot_M":             "5 9 years Total Males",
	"A_5_9_y_Tot_F":             "5 9 years Total Females",
	"A_5_9_y_Tot_P":             "5 9 years Total Persons",
	"A_10_14_y_Indigenous_M":    "10 14 years Aboriginal and or Torres Strait Islander Males",
	"A_10_14_y_Indigenous_F":    "10 14 years Aboriginal and or Torres Strait Islander Females",
	"A_10_14_y_Indigenous_P":    "10 14 years Aboriginal and or Torres Strait Islander Persons",
	"A_10_14_y_Non_Indig_M":     "10 14 years Non Indigenous Males",
	"A_10_14_y_Non_Indig_F":     "10 14 years Non Indigenous Females",
	"A_10_14_y_Non_Indig_P":     "10 14 years Non Indigenous Persons",
	"A_10_14_y_Indig_stat_ns_M": "10 14 years Indigenous status not stated Males",
	"A_10_14_y_Indig_stat_ns_F": "10 14 years Indigenous status not stated Females",
	"A_10_14_y_Indig_stat_ns_P": "10 14 years Indigenous status not stated Persons",
	"A_10_14_y_Tot_M":           "10 14 years Total Males",
	"A_10_14_y_Tot_F":           "10 14 years Total Females",
	"A_10_14_y_Tot_P":           "10 14 years Total Persons",
	"A_15_19_y_Indigenous_M":    "15 19 years Aboriginal and or Torres Strait Islander Males",
	"A_15_19_y_Indigenous_F":    "15 19 years Aboriginal and or Torres Strait Islander Females",
	"A_15_19_y_Indigenous_P":    "15 19 years Aboriginal and or Torres Strait Islander Persons",
	"A_15_19_y_Non_Indig_M":     "15 19 years Non Indigenous Males",
	"A_15_19_y_Non_Indig_F":     "15 19 years Non Indigenous Females",
	"A_15_19_y_Non_Indig_P":     "15 19 years Non Indigenous Persons",
	"A_15_19_y_Indig_stat_ns_M": "15 19 years Indigenous status not stated Males",
	"A_15_19_y_Indig_stat_ns_F": "15 19 years Indigenous status not stated Females",
	"A_15_19_y_Indig_stat_ns_P": "15 19 years Indigenous status not stated Persons",
	"A_15_19_y_Tot_M":           "15 19 years Total Males",
	"A_15_19_y_Tot_F":           "15 19 years Total Females",
	"A_15_19_y_Tot_P":           "15 19 years Total Persons",
	"A_20_24_y_Indigenous_M":    "20 24 years Aboriginal and or Torres Strait Islander Males",
	"A_20_24_y_Indigenous_F":    "20 24 years Aboriginal and or Torres Strait Islander Females",
	"A_20_24_y_Indigenous_P":    "20 24 years Aboriginal and or Torres Strait Islander Persons",
	"A_20_24_y_Non_Indig_M":     "20 24 years Non Indigenous Males",
	"A_20_24_y_Non_Indig_F":     "20 24 years Non Indigenous Females",
	"A_20_24_y_Non_Indig_P":     "20 24 years Non Indigenous Persons",
	"A_20_24_y_Indig_stat_ns_M": "20 24 years Indigenous status not stated Males",
	"A_20_24_y_Indig_stat_ns_F": "20 24 years Indigenous status not stated Females",
	"A_20_24_y_Indig_stat_ns_P": "20 24 years Indigenous status not stated Persons",
	"A_20_24_y_Tot_M":           "20 24 years Total Males",
	"A_20_24_y_Tot_F":           "20 24 years Total Females",
	"A_20_24_y_Tot_P":           "20 24 years Total Persons",
	"A_25_29_y_Indigenous_M":    "25 29 years Aboriginal and or Torres Strait Islander Males",
	"A_25_29_y_Indigenous_F":    "25 29 years Aboriginal and or Torres Strait Islander Females",
	"A_25_29_y_Indigenous_P":    "25 29 years Aboriginal and or Torres Strait Islander Persons",
	"A_25_29_y_Non_Indig_M":     "25 29 years Non Indigenous Males",
	"A_25_29_y_Non_Indig_F":     "25 29 years Non Indigenous Females",
	"A_25_29_y_Non_Indig_P":     "25 29 years Non Indigenous Persons",
	"A_25_29_y_Indig_stat_ns_M": "25 29 years Indigenous status not stated Males",
	"A_25_29_y_Indig_stat_ns_F": "25 29 years Indigenous status not stated Females",
	"A_25_29_y_Indig_stat_ns_P": "25 29 years Indigenous status not stated Persons",
	"A_25_29_y_Tot_M":           "25 29 years Total Males",
	"A_25_29_y_Tot_F":           "25 29 years Total Females",
	"A_25_29_y_Tot_P":           "25 29 years Total Persons",
	"A_30_34_y_Indigenous_M":    "30 34 years Aboriginal and or Torres Strait Islander Males",
	"A_30_34_y_Indigenous_F":    "30 34 years Aboriginal and or Torres Strait Islander Females",
	"A_30_34_y_Indigenous_P":    "30 34 years Aboriginal and or Torres Strait Islander Persons",
	"A_30_34_y_Non_Indig_M":     "30 34 years Non Indigenous Males",
	"A_30_34_y_Non_Indig_F":     "30 34 years Non Indigenous Females",
	"A_30_34_y_Non_Indig_P":     "30 34 years Non Indigenous Persons",
	"A_30_34_y_Indig_stat_ns_M": "30 34 years Indigenous status not stated Males",
	"A_30_34_y_Indig_stat_ns_F": "30 34 years Indigenous status not stated Females",
	"A_30_34_y_Indig_stat_ns_P": "30 34 years Indigenous status not stated Persons",
	"A_30_34_y_Tot_M":           "30 34 years Total Males",
	"A_30_34_y_Tot_F":           "30 34 years Total Females",
	"A_30_34_y_Tot_P":           "30 34 years Total Persons",
	"A_35_39_y_Indigenous_M":    "35 39 years Aboriginal and or Torres Strait Islander Males",
	"A_35_39_y_Indigenous_F":    "35 39 years Aboriginal and or Torres Strait Islander Females",
	"A_35_39_y_Indigenous_P":    "35 39 years Aboriginal and or Torres Strait Islander Persons",
	"A_35_39_y_Non_Indig_M":     "35 39 years Non Indigenous Males",
	"A_35_39_y_Non_Indig_F":     "35 39 years Non Indigenous Females",
	"A_35_39_y_Non_Indig_P":     "35 39 years Non Indigenous Persons",
	"A_35_39_y_Indig_stat_ns_M": "35 39 years Indigenous status not stated Males",
	"A_35_39_y_Indig_stat_ns_F": "35 39 years Indigenous status not stated Females",
	"A_35_39_y_Indig_stat_ns_P": "35 39 years Indigenous status not stated Persons",
	"A_35_39_y_Tot_M":           "35 39 years Total Males",
	"A_35_39_y_Tot_F":           "35 39 years Total Females",
	"A_35_39_y_Tot_P":           "35 39 years Total Persons",
	"A_40_44_y_Indigenous_M":    "40 44 years Aboriginal and or Torres Strait Islander Males",
	"A_40_44_y_Indigenous_F":    "40 44 years Aboriginal and or Torres Strait Islander Females",
	"A_40_44_y_Indigenous_P":    "40 44 years Aboriginal and or Torres Strait Islander Persons",
	"A_40_44_y_Non_Indig_M":     "40 44 years Non Indigenous Males",
	"A_40_44_y_Non_Indig_F":     "40 44 years Non Indigenous Females",
	"A_40_44_y_Non_Indig_P":     "40 44 years Non Indigenous Persons",
	"A_40_44_y_Indig_stat_ns_M": "40 44 years Indigenous status not stated Males",
	"A_40_44_y_Indig_stat_ns_F": "40 44 years Indigenous status not stated Females",
	"A_40_44_y_Indig_stat_ns_P": "40 44 years Indigenous status not stated Persons",
	"A_40_44_y_Tot_M":           "40 44 years Total Males",
	"A_40_44_y_Tot_F":           "40 44 years Total Females",
	"A_40_44_y_Tot_P":           "40 44 years Total Persons",
	"A_45_49_y_Indigenous_M":    "45 49 years Aboriginal and or Torres Strait Islander Males",
	"A_45_49_y_Indigenous_F":    "45 49 years Aboriginal and or Torres Strait Islander Females",
	"A_45_49_y_Indigenous_P":    "45 49 years Aboriginal and or Torres Strait Islander Persons",
	"A_45_49_y_Non_Indig_M":     "45 49 years Non Indigenous Males",
	"A_45_49_y_Non_Indig_F":     "45 49 years Non Indigenous Females",
	"A_45_49_y_Non_Indig_P":     "45 49 years Non Indigenous Persons",
	"A_45_49_y_Indig_stat_ns_M": "45 49 years Indigenous status not stated Males",
	"A_45_49_y_Indig_stat_ns_F": "45 49 years Indigenous status not stated Females",
	"A_45_49_y_Indig_stat_ns_P": "45 49 years Indigenous status not stated Persons",
	"A_45_49_y_Tot_M":           "45 49 years Total Males",
	"A_45_49_y_Tot_F":           "45 49 years Total Females",
	"A_45_49_y_Tot_P":           "45 49 years Total Persons",
	"A_50_54_y_Indigenous_M":    "50 54 years Aboriginal and or Torres Strait Islander Males",
	"A_50_54_y_Indigenous_F":    "50 54 years Aboriginal and or Torres Strait Islander Females",
	"A_50_54_y_Indigenous_P":    "50 54 years Aboriginal and or Torres Strait Islander Persons",
	"A_50_54_y_Non_Indig_M":     "50 54 years Non Indigenous Males",
	"A_50_54_y_Non_Indig_F":     "50 54 years Non Indigenous Females",
	"A_50_54_y_Non_Indig_P":     "50 54 years Non Indigenous Persons",
	"A_50_54_y_Indig_stat_ns_M": "50 54 years Indigenous status not stated Males",
	"A_50_54_y_Indig_stat_ns_F": "50 54 years Indigenous status not stated Females",
	"A_50_54_y_Indig_stat_ns_P": "50 54 years Indigenous status not stated Persons",
	"A_50_54_y_Tot_M":           "50 54 years Total Males",
	"A_50_54_y_Tot_F":           "50 54 years Total Females",
	"A_50_54_y_Tot_P":           "50 54 years Total Persons",
	"A_55_59_y_Indigenous_M":    "55 59 years Aboriginal and or Torres Strait Islander Males",
	"A_55_59_y_Indigenous_F":    "55 59 years Aboriginal and or Torres Strait Islander Females",
	"A_55_59_y_Indigenous_P":    "55 59 years Aboriginal and or Torres Strait Islander Persons",
	"A_55_59_y_Non_Indig_M":     "55 59 years Non Indigenous Males",
	"A_55_59_y_Non_Indig_F":     "55 59 years Non Indigenous Females",
	"A_55_59_y_Non_Indig_P":     "55 59 years Non Indigenous Persons",
	"A_55_59_y_Indig_stat_ns_M": "55 59 years Indigenous status not stated Males",
	"A_55_59_y_Indig_stat_ns_F": "55 59 years Indigenous status not stated Females",
	"A_55_59_y_Indig_stat_ns_P": "55 59 years Indigenous status not stated Persons",
	"A_55_59_y_Tot_M":           "55 59 years Total Males",
	"A_55_59_y_Tot_F":           "55 59 years Total Females",
	"A_55_59_y_Tot_P":           "55 59 years Total Persons",
	"A_60_64_y_Indigenous_M":    "60 64 years Aboriginal and or Torres Strait Islander Males",
	"A_60_64_y_Indigenous_F":    "60 64 years Aboriginal and or Torres Strait Islander Females",
	"A_60_64_y_Indigenous_P":    "60 64 years Aboriginal and or Torres Strait Islander Persons",
	"A_60_64_y_Non_Indig_M":     "60 64 years Non Indigenous Males",
	"A_60_64_y_Non_Indig_F":     "60 64 years Non Indigenous Females",
	"A_60_64_y_Non_Indig_P":     "60 64 years Non Indigenous Persons",
	"A_60_64_y_Indig_stat_ns_M": "60 64 years Indigenous status not stated Males",
	"A_60_64_y_Indig_stat_ns_F": "60 64 years Indigenous status not stated Females",
	"A_60_64_y_Indig_stat_ns_P": "60 64 years Indigenous status not stated Persons",
	"A_60_64_y_Tot_M":           "60 64 years Total Males",
	"A_60_64_y_Tot_F":           "60 64 years Total Females",
	"A_60_64_y_Tot_P":           "60 64 years Total Persons",
	"A_65_y_ov_Indigenous_M":    "65 years and over Aboriginal and or Torres Strait Islander Males",
	"A_65_y_ov_Indigenous_F":    "65 years and over Aboriginal and or Torres Strait Islander Females",
	"A_65_y_ov_Indigenous_P":    "65 years and over Aboriginal and or Torres Strait Islander Persons",
	"A_65_y_ov_Non_Indig_M":     "65 years and over Non Indigenous Males",
	"A_65_y_ov_Non_Indig_F":     "65 years and over Non Indigenous Females",
	"A_65_y_ov_Non_Indig_P":     "65 years and over Non Indigenous Persons",
	"A_65_y_ov_Indig_stat_ns_M": "65 years and over Indigenous status not stated Males",
	"A_65_y_ov_Indig_stat_ns_F": "65 years and over Indigenous status not stated Females",
	"A_65_y_ov_Indig_stat_ns_P": "65 years and over Indigenous status not stated Persons",
	"A_65_y_ov_Tot_M":           "65 years and over Total Males",
	"A_65_y_ov_Tot_F":           "65 years and over Total Females",
	"A_65_y_ov_Tot_P":           "65 years and over Total Persons",
	"Tot_Indigenous_M":          "Total Aboriginal and or Torres Strait Islander Males",
	"Tot_Indigenous_F":          "Total Aboriginal and or Torres Strait Islander Females",
	"Tot_Indigenous_P":          "Total Aboriginal and or Torres Strait Islander Persons",
	"Tot_Non_Indigenous_M":      "Total Non Indigenous Males",
	"Tot_Non_Indigenous_F":      "Total Non Indigenous Females",
	"Tot_Non_Indigenous_P":      "Total Non Indigenous Persons",
	"Tot_Indig_status_ns_M":     "Total Indigenous status not stated Males",
	"Tot_Indig_status_ns_F":     "Total Indigenous status not stated Females",
	"Tot_Indig_status_ns_P":     "Total Indigenous status not stated Persons",
	"Tot_Tot_M":                 "Total Total Males",
	"Tot_Tot_F":                 "Total Total Females",
	"Tot_Tot_P":                 "Total Total Persons",
}

//G08 Ancestry by Country of Birth of Parents
var G08 = map[string]string{
	"Aust_BP_B_OS":                "Australian Both parents born overseas",
	"Aust_FO_B_OS":                "Australian Father only born overseas",
	"Aust_MO_B_OS":                "Australian Mother only born overseas",
	"Aust_Both_parents_born_Aust": "Australian Both parents born in Australia",
	"Aust_Birthplace_not_stated":  "Australian Birthplace not stated",
	"Aust_Tot_Resp":               "Australian Total Responses",
	"Aust_Abor_BP_B_OS":           "Australian Aboriginal Both parents born overseas",
	"Aust_Abor_FO_B_OS":           "Australian Aboriginal Father only born overseas",
	"Aust_Abor_MO_B_OS":           "Australian Aboriginal Mother only born overseas",
	"Aust_Abor_BP_B_Aus":          "Australian Aboriginal Both parents born in Australia",
	"Aust_Abor_BP_NS":             "Australian Aboriginal Birthplace not stated",
	"Aust_Abor_Tot_Resp":          "Australian Aboriginal Total Responses",
	"Chinese_BP_B_OS":             "Chinese Both parents born overseas",
	"Chinese_FO_B_OS":             "Chinese Father only born overseas",
	"Chinese_MO_B_OS":             "Chinese Mother only born overseas",
	"Chinese_BP_B_Aus":            "Chinese Both parents born in Australia",
	"Chinese_BP_NS":               "Chinese Birthplace not stated",
	"Chinese_Tot_Resp":            "Chinese Total Responses",
	"Croatian_BP_B_OS":            "Croatian Both parents born overseas",
	"Croatian_FO_B_OS":            "Croatian Father only born overseas",
	"Croatian_MO_B_OS":            "Croatian Mother only born overseas",
	"Croatian_BP_B_Aus":           "Croatian Both parents born in Australia",
	"Croatian_BP_NS":              "Croatian Birthplace not stated",
	"Croatian_Tot_Resp":           "Croatian Total Responses",
	"Dutch_BP_B_OS":               "Dutch Both parents born overseas",
	"Dutch_FO_B_OS":               "Dutch Father only born overseas",
	"Dutch_MO_B_OS":               "Dutch Mother only born overseas",
	"Dutch_BP_B_Aus":              "Dutch Both parents born in Australia",
	"Dutch_BP_NS":                 "Dutch Birthplace not stated",
	"Dutch_Tot_Resp":              "Dutch Total Responses",
	"English_BP_B_OS":             "English Both parents born overseas",
	"English_FO_B_OS":             "English Father only born overseas",
	"English_MO_B_OS":             "English Mother only born overseas",
	"English_BP_B_Aus":            "English Both parents born in Australia",
	"English_BP_NS":               "English Birthplace not stated",
	"English_Tot_Resp":            "English Total Responses",
	"Filipino_BP_B_OS":            "Filipino Both parents born overseas",
	"Filipino_FO_B_OS":            "Filipino Father only born overseas",
	"Filipino_MO_B_OS":            "Filipino Mother only born overseas",
	"Filipino_BP_B_Aus":           "Filipino Both parents born in Australia",
	"Filipino_BP_NS":              "Filipino Birthplace not stated",
	"Filipino_Tot_Resp":           "Filipino Total Responses",
	"French_BP_B_OS":              "French Both parents born overseas",
	"French_FO_B_OS":              "French Father only born overseas",
	"French_MO_B_OS":              "French Mother only born overseas",
	"French_BP_B_Aus":             "French Both parents born in Australia",
	"French_BP_NS":                "French Birthplace not stated",
	"French_Tot_Resp":             "French Total Responses",
	"German_BP_B_OS":              "German Both parents born overseas",
	"German_FO_B_OS":              "German Father only born overseas",
	"German_MO_B_OS":              "German Mother only born overseas",
	"German_BP_B_Aus":             "German Both parents born in Australia",
	"German_BP_NS":                "German Birthplace not stated",
	"German_Tot_Resp":             "German Total Responses",
	"Greek_BP_B_OS":               "Greek Both parents born overseas",
	"Greek_FO_B_OS":               "Greek Father only born overseas",
	"Greek_MO_B_OS":               "Greek Mother only born overseas",
	"Greek_BP_B_Aus":              "Greek Both parents born in Australia",
	"Greek_BP_NS":                 "Greek Birthplace not stated",
	"Greek_Tot_Resp":              "Greek Total Responses",
	"Hungarian_BP_B_OS":           "Hungarian Both parents born overseas",
	"Hungarian_FO_B_OS":           "Hungarian Father only born overseas",
	"Hungarian_MO_B_OS":           "Hungarian Mother only born overseas",
	"Hungarian_BP_B_Aus":          "Hungarian Both parents born in Australia",
	"Hungarian_BP_NS":             "Hungarian Birthplace not stated",
	"Hungarian_Tot_Resp":          "Hungarian Total Responses",
	"Indian_BP_B_OS":              "Indian Both parents born overseas",
	"Indian_FO_B_OS":              "Indian Father only born overseas",
	"Indian_MO_B_OS":              "Indian Mother only born overseas",
	"Indian_BP_B_Aus":             "Indian Both parents born in Australia",
	"Indian_BP_NS":                "Indian Birthplace not stated",
	"Indian_Tot_Resp":             "Indian Total Responses",
	"Irish_BP_B_OS":               "Irish Both parents born overseas",
	"Irish_FO_B_OS":               "Irish Father only born overseas",
	"Irish_MO_B_OS":               "Irish Mother only born overseas",
	"Irish_BP_B_Aus":              "Irish Both parents born in Australia",
	"Irish_BP_NS":                 "Irish Birthplace not stated",
	"Irish_Tot_Resp":              "Irish Total Responses",
	"Italian_BP_B_OS":             "Italian Both parents born overseas",
	"Italian_FO_B_OS":             "Italian Father only born overseas",
	"Italian_MO_B_OS":             "Italian Mother only born overseas",
	"Italian_BP_B_Aus":            "Italian Both parents born in Australia",
	"Italian_BP_NS":               "Italian Birthplace not stated",
	"Italian_Tot_Resp":            "Italian Total Responses",
	"Korean_BP_B_OS":              "Korean Both parents born overseas",
	"Korean_FO_B_OS":              "Korean Father only born overseas",
	"Korean_MO_B_OS":              "Korean Mother only born overseas",
	"Korean_BP_B_Aus":             "Korean Both parents born in Australia",
	"Korean_BP_NS":                "Korean Birthplace not stated",
	"Korean_Tot_Resp":             "Korean Total Responses",
	"Lebanese_BP_B_OS":            "Lebanese Both parents born overseas",
	"Lebanese_FO_B_OS":            "Lebanese Father only born overseas",
	"Lebanese_MO_B_OS":            "Lebanese Mother only born overseas",
	"Lebanese_BP_B_Aus":           "Lebanese Both parents born in Australia",
	"Lebanese_BP_NS":              "Lebanese Birthplace not stated",
	"Lebanese_Tot_Resp":           "Lebanese Total Responses",
	"Macedonian_BP_B_OS":          "Macedonian Both parents born overseas",
	"Macdonian_FO_B_OS":           "Macedonian Father only born overseas",
	"Macdonian_MO_B_OS":           "Macedonian Mother only born overseas",
	"Macdonian_BP_B_Aus":          "Macedonian Both parents born in Australia",
	"Macdonian_BP_NS":             "Macedonian Birthplace not stated",
	"Macedonian_Tot_Resp":         "Macedonian Total Responses",
	"Maltese_BP_B_OS":             "Maltese Both parents born overseas",
	"Maltese_FO_B_OS":             "Maltese Father only born overseas",
	"Maltese_MO_B_OS":             "Maltese Mother only born overseas",
	"Maltese_BP_B_Aus":            "Maltese Both parents born in Australia",
	"Maltese_BP_NS":               "Maltese Birthplace not stated",
	"Maltese_Tot_Resp":            "Maltese Total Responses",
	"Maori_BP_B_OS":               "Maori Both parents born overseas",
	"Maori_FO_B_OS":               "Maori Father only born overseas",
	"Maori_MO_B_OS":               "Maori Mother only born overseas",
	"Maori_BP_B_Aus":              "Maori Both parents born in Australia",
	"Maori_BP_NS":                 "Maori Birthplace not stated",
	"Maori_Tot_Resp":              "Maori Total Responses",
	"NZ_BP_B_OS":                  "New Zealander Both parents born overseas",
	"NZ_FO_B_OS":                  "New Zealander Father only born overseas",
	"NZ_MO_B_OS":                  "New Zealander Mother only born overseas",
	"NZ_BP_B_Aus":                 "New Zealander Both parents born in Australia",
	"NZ_BP_NS":                    "New Zealander Birthplace not stated",
	"NZ_Tot_Resp":                 "New Zealander Total Responses",
	"Polish_BP_B_OS":              "Polish Both parents born overseas",
	"Polish_FO_B_OS":              "Polish Father only born overseas",
	"Polish_MO_B_OS":              "Polish Mother only born overseas",
	"Polish_BP_B_Aus":             "Polish Both parents born in Australia",
	"Polish_BP_NS":                "Polish Birthplace not stated",
	"Polish_Tot_Resp":             "Polish Total Responses",
	"Russian_BP_B_OS":             "Russian Both parents born overseas",
	"Russian_FO_B_OS":             "Russian Father only born overseas",
	"Russian_MO_B_OS":             "Russian Mother only born overseas",
	"Russian_BP_B_Aus":            "Russian Both parents born in Australia",
	"Russian_BP_NS":               "Russian Birthplace not stated",
	"Russian_Tot_Resp":            "Russian Total Responses",
	"Scottish_BP_B_OS":            "Scottish Both parents born overseas",
	"Scottish_FO_B_OS":            "Scottish Father only born overseas",
	"Scottish_MO_B_OS":            "Scottish Mother only born overseas",
	"Scottish_BP_B_Aus":           "Scottish Both parents born in Australia",
	"Scottish_BP_NS":              "Scottish Birthplace not stated",
	"Scottish_Tot_Resp":           "Scottish Total Responses",
	"Serbian_BP_B_OS":             "Serbian Both parents born overseas",
	"Serbian_FO_B_OS":             "Serbian Father only born overseas",
	"Serbian_MO_B_OS":             "Serbian Mother only born overseas",
	"Serbian_BP_B_Aus":            "Serbian Both parents born in Australia",
	"Serbian_BP_NS":               "Serbian Birthplace not stated",
	"Serbian_Tot_Resp":            "Serbian Total Responses",
	"Sth_African_BP_B_OS":         "South African Both parents born overseas",
	"Sth_African_FO_B_OS":         "South African Father only born overseas",
	"Sth_African_MO_B_OS":         "South African Mother only born overseas",
	"Sth_Afrcan_BP_B_Aus":         "South African Both parents born in Australia",
	"Sth_African_BP_NS":           "South African Birthplace not stated",
	"Sth_African_Tot_Resp":        "South African Total Responses",
	"Spanish_BP_B_OS":             "Spanish Both parents born overseas",
	"Spanish_FO_B_OS":             "Spanish Father only born overseas",
	"Spanish_MO_B_OS":             "Spanish Mother only born overseas",
	"Spanish_BP_B_Aus":            "Spanish Both parents born in Australia",
	"Spanish_BP_NS":               "Spanish Birthplace not stated",
	"Spanish_Tot_Resp":            "Spanish Total Responses",
	"Sri_Lankan_BP_B_OS":          "Sri Lankan Both parents born overseas",
	"Sri_Lankan_FO_B_OS":          "Sri Lankan Father only born overseas",
	"Sri_Lankan_MO_B_OS":          "Sri Lankan Mother only born overseas",
	"Sri_Lankan_BP_B_Aus":         "Sri Lankan Both parents born in Australia",
	"Sri_Lankan_BP_NS":            "Sri Lankan Birthplace not stated",
	"Sri_Lankan_Tot_Resp":         "Sri Lankan Total Responses",
	"Turkish_BP_B_OS":             "Turkish Both parents born overseas",
	"Turkish_FO_B_OS":             "Turkish Father only born overseas",
	"Turkish_MO_B_OS":             "Turkish Mother only born overseas",
	"Turkish_BP_B_Aus":            "Turkish Both parents born in Australia",
	"Turkish_BP_NS":               "Turkish Birthplace not stated",
	"Turkish_Tot_Resp":            "Turkish Total Responses",
	"Vietnamese_BP_B_OS":          "Vietnamese Both parents born overseas",
	"Vietnamese_FO_B_OS":          "Vietnamese Father only born overseas",
	"Vietnamese_MO_B_OS":          "Vietnamese Mother only born overseas",
	"Vietnamese_BP_B_Aus":         "Vietnamese Both parents born in Australia",
	"Vietnamese_BP_NS":            "Vietnamese Birthplace not stated",
	"Vietnamese_Tot_Resp":         "Vietnamese Total Responses",
	"Welsh_BP_B_OS":               "Welsh Both parents born overseas",
	"Welsh_FO_B_OS":               "Welsh Father only born overseas",
	"Welsh_MO_B_OS":               "Welsh Mother only born overseas",
	"Welsh_BP_B_Aus":              "Welsh Both parents born in Australia",
	"Welsh_BP_NS":                 "Welsh Birthplace not stated",
	"Welsh_Tot_Resp":              "Welsh Total Responses",
	"Other_BP_B_OS":               "Other Both parents born overseas",
	"Other_FO_B_OS":               "Other Father only born overseas",
	"Other_MO_B_OS":               "Other Mother only born overseas",
	"Other_BP_B_Aus":              "Other Both parents born in Australia",
	"Other_BP_NS":                 "Other Birthplace not stated",
	"Other_Tot_Resp":              "Other Total Responses",
	"Ancestry_NS_BP_B_OS":         "Ancestry not stated Both parents born overseas",
	"Ancestry_NS_FO_B_OS":         "Ancestry not stated Father only born overseas",
	"Ancestry_NS_MO_B_OS":         "Ancestry not stated Mother only born overseas",
	"Ancestry_NS_BP_B_Aus":        "Ancestry not stated Both parents born in Australia",
	"Ancestry_NS_BP_NS":           "Ancestry not stated Birthplace not stated",
	"Ancestry_NS_Tot_Resp":        "Ancestry not stated Total Responses",
	"Tot_P_BP_B_OS":               "Total Persons Both parents born overseas",
	"Tot_P_FO_B_OS":               "Total Persons Father only born overseas",
	"Tot_P_MO_B_OS":               "Total Persons Mother only born overseas",
	"Tot_P_BP_B_Aus":              "Total Persons Both parents born in Australia",
	"Tot_P_BP_NS":                 "Total Persons Birthplace not stated",
	"Tot_P_Tot_Resp":              "Total Persons Total Responses",
}

//G25 Family Composition
var G25 = map[string]string{
	"CF_no_children_F":              "Couple family with no children Families",
	"CF_no_children_P":              "Couple family with no children Persons",
	"CF_ChU15_a_DSs_a_NdCh_F":       "Couple family with children under 15 and dependent students and non dependent children Families",
	"CF_ChU15_a_DSs_a_NdCh_P":       "Couple family with children under 15 and dependent students and non dependent children Persons",
	"CF_ChU15_a_DSs_a_no_NdCh_F":    "Couple family with children under 15 and dependent students and no non dependent children Families",
	"CF_ChU15_a_DSs_a_no_NdCh_P":    "Couple family with children under 15 and dependent students and no non dependent children Persons",
	"CF_ChU15_a_no_DSs_a_NdCh_F":    "Couple family with children under 15 and no dependent students and non dependent children Families",
	"CF_ChU15_a_no_DSs_a_NdCh_P":    "Couple family with children under 15 and no dependent students and non dependent children Persons",
	"CF_ChU15_a_no_DSs_a_no_NdCh_F": "Couple family with children under 15 and no dependent students and no non dependent children Families",
	"CF_ChU15_a_no_DSs_a_no_NdCh_P": "Couple family with children under 15 and no dependent students and no non dependent children Persons",
	"CF_ChU15_a_Total_F":            "Couple family with children under 15 and Total Families",
	"CF_ChU15_a_Total_P":            "Couple family with children under 15 and Total Persons",
	"CF_no_ChU15_a_DSs_a_NdCh_F":    "Couple family with no children under 15 and dependent students and non dependent children Families",
	"CF_no_ChU15_a_DSs_a_NdCh_P":    "Couple family with no children under 15 and dependent students and non dependent children Persons",
	"CF_no_ChU15_a_DSs_a_no_NdCh_F": "Couple family with no children under 15 and dependent students and no non dependent children Families",
	"CF_no_ChU15_a_DSs_a_no_NdCh_P": "Couple family with no children under 15 and dependent students and no non dependent children Persons",
	"CF_no_ChU15_a_no_DSs_a_NdCh_F": "Couple family with no children under 15 and no dependent students and non dependent children Families",
	"CF_no_ChU15_a_no_DSs_a_NdCh_P": "Couple family with no children under 15 and no dependent students and non dependent children Persons",
	"CF_no_ChU15_a_Total_F":         "Couple family with no children under 15 and Total Families",
	"CF_no_ChU15_a_Total_P":         "Couple family with no children under 15 and Total Persons",
	"CF_Total_F":                    "Couple family with Total Families",
	"CF_Total_P":                    "Couple family with Total Persons",
	"OPF_ChU15_a_DSs_a_NdCh_F":      "One parent family with children under 15 and dependent students and non dependent children Families",
	"OPF_ChU15_a_DSs_a_NdCh_P":      "One parent family with children under 15 and dependent students and non dependent children Persons",
	"OPF_ChU15_a_DSs_a_no_NdCh_F":   "One parent family with children under 15 and dependent students and no non dependent children Families",
	"OPF_ChU15_a_DSs_a_no_NdCh_P":   "One parent family with children under 15 and dependent students and no non dependent children Persons",
	"OPF_ChU15_a_no_DSs_a_NdCh_F":   "One parent family with children under 15 and no dependent students and non dependent children Families",
	"OPF_ChU15_a_no_DSs_a_NdCh_P":   "One parent family with children under 15 and no dependent students and non dependent children Persons",
	"OPF_ChU15_a_no_DSs_no_NdCh_F":  "One parent family with children under 15 and no dependent students and no non dependent children Families",
	"OPF_ChU15_a_no_DSs_no_NdCh_P":  "One parent family with children under 15 and no dependent students and no non dependent children Persons",
	"OPF_ChU15_a_Total_F":           "One parent family with children under 15 and Total Families",
	"OPF_ChU15_a_Total_P":           "One parent family with children under 15 and Total Persons",
	"OPF_no_ChU15_a_DSs_a_NdCh_F":   "One parent family with no children under 15 and dependent students and non dependent children Families",
	"OPF_no_ChU15_a_DSs_a_NdCh_P":   "One parent family with no children under 15 and dependent students and non dependent children Persons",
	"OPF_no_ChU15_a_DSs_no_NdCh_F":  "One parent family with no children under 15 and dependent students and no non dependent children Families",
	"OPF_no_ChU15_a_DSs_no_NdCh_P":  "One parent family with no children under 15 and dependent students and no non dependent children Persons",
	"OPF_no_ChU15_no_DSs_a_NdCh_F":  "One parent family with no children under 15 and no dependent students and non dependent children Families",
	"OPF_no_ChU15_no_DSs_a_NdCh_P":  "One parent family with no children under 15 and no dependent students and non dependent children Persons",
	"OPF_no_ChU15_a_Total_F":        "One parent family with no children under 15 and Total Families",
	"OPF_no_ChU15_a_Total_P":        "One parent family with no children under 15 and Total Persons",
	"OPF_Total_F":                   "One parent family with Total Families",
	"OPF_Total_P":                   "One parent family with Total Persons",
	"Other_family_F":                "Other family Families",
	"Other_family_P":                "Other family Persons",
	"Total_F":                       "Total Families",
	"Total_P":                       "Total Persons",
}

//G27 Family Blending
var G27 = map[string]string{
	"Intct_fam_no_otr_chld_pre_Fam": "Intact family with no other children present Families",
	"Step_fam_no_otr_chld_pre_Fam":  "Step family with no other children present Families",
	"Blnd_fam_no_otr_chld_pre_Fam":  "Blended family with no other children present Families",
	"Intct_fam_othr_child_pres_Fam": "Intact family with other children present Families",
	"Step_fam_othr_child_pres_Fam":  "Step family with other children present Families",
	"Blnd_fam_othr_child_pres_Fam":  "Blended family with other children present Families",
	"Otr_cpl_fam_otr_chld_only_Fam": "Other couple family with other children only Families",
	"Tot_Families":                  "Total Families",
}

//G28 Total Family Income (Weekly) by Family Composition
var G28 = map[string]string{
	"Neg_Nil_inc_cpl_fam_no_child":  "Negative Nil income Couple family with no children",
	"Neg_Nil_inc_cpl_fam_wth_chld":  "Negative Nil income Couple family with children",
	"Neg_Nil_inc_One_parent_fam":    "Negative Nil income One parent family",
	"Neg_Nil_inc_Other_fam":         "Negative Nil income Other family",
	"Neg_Nil_inc_Tot":               "Negative Nil income Total",
	"FI_1_149_cpl_fam_no_child":     "1 149 Couple family with no children",
	"FI_1_149_cpl_fam_with_child":   "1 149 Couple family with children",
	"FI_1_149_One_parent_fam":       "1 149 One parent family",
	"FI_1_149_Other_fam":            "1 149 Other family",
	"FI_1_149_Tot":                  "1 149 Total",
	"FI_150_299_cpl_fam_no_child":   "150 299 Couple family with no children",
	"FI_150_299_cpl_fam_with_child": "150 299 Couple family with children",
	"FI_150_299_One_parent_fam":     "150 299 One parent family",
	"FI_150_299_Other_fam":          "150 299 Other family",
	"FI_150_299_Tot":                "150 299 Total",
	"FI_300_399_cpl_fam_no_child":   "300 399 Couple family with no children",
	"FI_300_399_cpl_fam_with_child": "300 399 Couple family with children",
	"FI_300_399_One_parent_fam":     "300 399 One parent family",
	"FI_300_399_Other_fam":          "300 399 Other family",
	"FI_300_399_Tot":                "300 399 Total",
	"FI_400_499_cpl_fam_no_child":   "400 499 Couple family with no children",
	"FI_400_499_cpl_fam_with_child": "400 499 Couple family with children",
	"FI_400_499_One_parent_fam":     "400 499 One parent family",
	"FI_400_499_Other_fam":          "400 499 Other family",
	"FI_400_499_Tot":                "400 499 Total",
	"FI_500_649_cpl_fam_no_child":   "500 649 Couple family with no children",
	"FI_500_649_cpl_fam_with_child": "500 649 Couple family with children",
	"FI_500_649_One_parent_fam":     "500 649 One parent family",
	"FI_500_649_Other_fam":          "500 649 Other family",
	"FI_500_649_Tot":                "500 649 Total",
	"FI_650_799_cpl_fam_no_child":   "650 799 Couple family with no children",
	"FI_650_799_cpl_fam_with_child": "650 799 Couple family with children",
	"FI_650_799_One_parent_fam":     "650 799 One parent family",
	"FI_650_799_Other_fam":          "650 799 Other family",
	"FI_650_799_Tot":                "650 799 Total",
	"FI_800_999_cpl_fam_no_child":   "800 999 Couple family with no children",
	"FI_800_999_cpl_fam_wth_chld":   "800 999 Couple family with children",
	"FI_800_999_One_parent_fam":     "800 999 One parent family",
	"FI_800_999_Other_fam":          "800 999 Other family",
	"FI_800_999_Tot":                "800 999 Total",
	"FI_1000_1249_cpl_fam_no_child": "1000 1249 Couple family with no children",
	"FI_1000_1249_cpl_fam_wth_chld": "1000 1249 Couple family with children",
	"FI_1000_1249_One_parent_fam":   "1000 1249 One parent family",
	"FI_1000_1249_Other_fam":        "1000 1249 Other family",
	"FI_1000_1249_Tot":              "1000 1249 Total",
	"FI_1250_1499_cpl_fam_no_child": "1250 1499 Couple family with no children",
	"FI_1250_1499_cpl_fam_wth_chld": "1250 1499 Couple family with children",
	"FI_1250_1499_One_parent_fam":   "1250 1499 One parent family",
	"FI_1250_1499_Other_fam":        "1250 1499 Other family",
	"FI_1250_1499_Tot":              "1250 1499 Total",
	"FI_1500_1749_cpl_fam_no_child": "1500 1749 Couple family with no children",
	"FI_1500_1749_cpl_fam_wth_chld": "1500 1749 Couple family with children",
	"FI_1500_1749_One_parent_fam":   "1500 1749 One parent family",
	"FI_1500_1749_Other_fam":        "1500 1749 Other family",
	"FI_1500_1749_Tot":              "1500 1749 Total",
	"FI_1750_1999_cpl_fam_no_child": "1750 1999 Couple family with no children",
	"FI_1750_1999_cpl_fam_wth_chld": "1750 1999 Couple family with children",
	"FI_1750_1999_One_parent_fam":   "1750 1999 One parent family",
	"FI_1750_1999_Other_fam":        "1750 1999 Other family",
	"FI_1750_1999_Tot":              "1750 1999 Total",
	"FI_2000_2499_cpl_fam_no_child": "2000 2499 Couple family with no children",
	"FI_2000_2499_cpl_fam_wth_chld": "2000 2499 Couple family with children",
	"FI_2000_2499_One_parent_fam":   "2000 2499 One parent family",
	"FI_2000_2499_Other_fam":        "2000 2499 Other family",
	"FI_2000_2499_Tot":              "2000 2499 Total",
	"FI_2500_2999_cpl_fam_no_child": "2500 2999 Couple family with no children",
	"FI_2500_2999_cpl_fam_wth_chld": "2500 2999 Couple family with children",
	"FI_2500_2999_One_parent_fam":   "2500 2999 One parent family",
	"FI_2500_2999_Other_fam":        "2500 2999 Other family",
	"FI_2500_2999_Tot":              "2500 2999 Total",
	"FI_3000_3499_cpl_fam_no_child": "3000 3499 Couple family with no children",
	"FI_3000_3499_cpl_fam_wth_chld": "3000 3499 Couple family with children",
	"FI_3000_3499_One_parent_fam":   "3000 3499 One parent family",
	"FI_3000_3499_Other_fam":        "3000 3499 Other family",
	"FI_3000_3499_Tot":              "3000 3499 Total",
	"FI_3500_3999_cpl_fam_no_child": "3500 3999 Couple family with no children",
	"FI_3500_3999_cpl_fam_wth_chld": "3500 3999 Couple family with children",
	"FI_3500_3999_One_parent_fam":   "3500 3999 One parent family",
	"FI_3500_3999_Other_fam":        "3500 3999 Other family",
	"FI_3500_3999_Tot":              "3500 3999 Total",
	"FI_4000_more_cpl_fam_no_child": "4000 or more Couple family with no children",
	"FI_4000_more_cpl_fam_wth_chld": "4000 or more Couple family with children",
	"FI_4000_more_One_parent_fam":   "4000 or more One parent family",
	"FI_4000_more_Other_fam":        "4000 or more Other family",
	"FI_4000_more_Tot":              "4000 or more Total",
	"Prt_inc_std_cpl_fam_no_child":  "Partial income stated Couple family with no children",
	"Part_inc_std_cpl_fam_wth_chld": "Partial income stated Couple family with children",
	"Part_inc_statd_One_parent_fam": "Partial income stated One parent family",
	"Partial_income_statd_Othr_fam": "Partial income stated Other family",
	"Partial_income_stated_Tot":     "Partial income stated Total",
	"All_inc_ns_cpl_fam_no_child":   "All incomes not stated Couple family with no children",
	"All_inc_ns_cpl_fam_wth_chld":   "All incomes not stated Couple family with children",
	"All_incomes_ns_One_parent_fam": "All incomes not stated One parent family",
	"All_incomes_ns_Other_fam":      "All incomes not stated Other family",
	"All_incomes_ns_Tot":            "All incomes not stated Total",
	"Tot_cpl_fam_no_child":          "Total Couple family with no children",
	"Tot_cpl_fam_wth_chld":          "Total Couple family with children",
	"Tot_One_parent_fam":            "Total One parent family",
	"Tot_Other_fam":                 "Total Other family",
	"Tot_Tot":                       "Total Total",
}

//G29 Total Household Income (Weekly) by Household Composition
var G29 = map[string]string{
	"Neg_Nil_inc_fam_households":    "Negative Nil income Family households",
	"Neg_Nil_inc_Non_fam_househlds": "Negative Nil income Non family households",
	"Negative_Nil_income_Tot":       "Negative Nil income Total",
	"HI_1_149_Family_households":    "1 149 Family households",
	"HI_1_149_Non_family_hseholds":  "1 149 Non family households",
	"HI_1_149_Tot":                  "1 149 Total",
	"HI_150_299_Family_households":  "150 299 Family households",
	"HI_150_299_Non_fam_househlds":  "150 299 Non family households",
	"HI_150_299_Tot":                "150 299 Total",
	"HI_300_399_Family_households":  "300 399 Family households",
	"HI_300_399_Non_fam_househlds":  "300 399 Non family households",
	"HI_300_399_Tot":                "300 399 Total",
	"HI_400_499_Family_households":  "400 499 Family households",
	"HI_400_499_Non_fam_househlds":  "400 499 Non family households",
	"HI_400_499_Tot":                "400 499 Total",
	"HI_500_649_Family_households":  "500 649 Family households",
	"HI_500_649_Non_fam_househlds":  "500 649 Non family households",
	"HI_500_649_Tot":                "500 649 Total",
	"HI_650_799_Family_households":  "650 799 Family households",
	"HI_650_799_Non_fam_househlds":  "650 799 Non family households",
	"HI_650_799_Tot":                "650 799 Total",
	"HI_800_999_Fam_households":     "800 999 Family households",
	"HI_800_999_Non_fam_hsehlds":    "800 999 Non family households",
	"HI_800_999_Tot":                "800 999 Total",
	"HI_1000_1249_Fam_households":   "1000 1249 Family households",
	"HI_1000_1249_Non_fam_hsehlds":  "1000 1249 Non family households",
	"HI_1000_1249_Tot":              "1000 1249 Total",
	"HI_1250_1499_Fam_households":   "1250 1499 Family households",
	"HI_1250_1499_Non_fam_hsehlds":  "1250 1499 Non family households",
	"HI_1250_1499_Tot":              "1250 1499 Total",
	"HI_1500_1749_Fam_households":   "1500 1749 Family households",
	"HI_1500_1749_Non_fam_hsehlds":  "1500 1749 Non family households",
	"HI_1500_1749_Tot":              "1500 1749 Total",
	"HI_1750_1999_Fam_households":   "1750 1999 Family households",
	"HI_1750_1999_Non_fam_hsehlds":  "1750 1999 Non family households",
	"HI_1750_1999_Tot":              "1750 1999 Total",
	"HI_2000_2499_Fam_households":   "2000 2499 Family households",
	"HI_2000_2499_Non_fam_hsehlds":  "2000 2499 Non family households",
	"HI_2000_2499_Tot":              "2000 2499 Total",
	"HI_2500_2999_Fam_households":   "2500 2999 Family households",
	"HI_2500_2999_Non_fam_hsehlds":  "2500 2999 Non family households",
	"HI_2500_2999_Tot":              "2500 2999 Total",
	"HI_3000_3499_Fam_households":   "3000 3499 Family households",
	"HI_3000_3499_Non_fam_hsehlds":  "3000 3499 Non family households",
	"HI_3000_3499_Tot":              "3000 3499 Total",
	"HI_3500_3999_Fam_households":   "3500 3999 Family households",
	"HI_3500_3999_Non_fam_hsehlds":  "3500 3999 Non family households",
	"HI_3500_3999_Tot":              "3500 3999 Total",
	"HI_4000_more_Fam_households":   "4000 or more Family households",
	"HI_4000_more_Non_fam_hsehlds":  "4000 or more Non family households",
	"HI_4000_more_Tot":              "4000 or more Total",
	"Part_inc_stated_Fam_household": "Partial income stated Family households",
	"Part_inc_std_Non_fam_hhds":     "Partial income stated Non family households",
	"Partial_income_stated_Tot":     "Partial income stated Total",
	"All_incomes_ns_Famly_househld": "All incomes not stated Family households",
	"All_inc_ns_Non_famly_househld": "All incomes not stated Non family households",
	"All_incomes_not_stated_Tot":    "All incomes not stated Total",
	"Tot_Family_households":         "Total Family households",
	"Tot_Non_family_households":     "Total Non family households",
	"Tot_Tot":                       "Total Total",
}

//G30 Number of Motor Vehicles by Dwellings
var G30 = map[string]string{
	"Num_MVs_per_dweling_0_MVs":   "Number of motor vehicles per dwelling No motor vehicles Dwellings",
	"Num_MVs_per_dweling_1_MVs":   "Number of motor vehicles per dwelling One motor vehicle Dwellings",
	"Num_MVs_per_dweling_2_MVs":   "Number of motor vehicles per dwelling Two motor vehicles Dwellings",
	"Num_MVs_per_dweling_3_MVs":   "Number of motor vehicles per dwelling Three motor vehicles Dwellings",
	"Num_MVs_per_dweling_4mo_MVs": "Number of motor vehicles per dwelling Four or more motor vehicles Dwellings",
	"Num_MVs_per_dweling_Tot":     "Number of motor vehicles per dwelling Total Dwellings",
	"Num_MVs_NS":                  "Number of motor vehicles not stated Dwellings",
	"Total_dwelings":              "Total Dwellings",
}

//G31 Household Composition by Number of Persons Usually Resident
var G31 = map[string]string{
	"Num_Psns_UR_1_FamHhold":      "Number of Persons usually resident One Family households",
	"Num_Psns_UR_1_NonFamHhold":   "Number of Persons usually resident One Non family households",
	"Num_Psns_UR_1_Total":         "Number of Persons usually resident One Total",
	"Num_Psns_UR_2_FamHhold":      "Number of Persons usually resident Two Family households",
	"Num_Psns_UR_2_NonFamHhold":   "Number of Persons usually resident Two Non family households",
	"Num_Psns_UR_2_Total":         "Number of Persons usually resident Two Total",
	"Num_Psns_UR_3_FamHhold":      "Number of Persons usually resident Three Family households",
	"Num_Psns_UR_3_NonFamHhold":   "Number of Persons usually resident Three Non family households",
	"Num_Psns_UR_3_Total":         "Number of Persons usually resident Three Total",
	"Num_Psns_UR_4_FamHhold":      "Number of Persons usually resident Four Family households",
	"Num_Psns_UR_4_NonFamHhold":   "Number of Persons usually resident Four Non family households",
	"Num_Psns_UR_4_Total":         "Number of Persons usually resident Four Total",
	"Num_Psns_UR_5_FamHhold":      "Number of Persons usually resident Five Family households",
	"Num_Psns_UR_5_NonFamHhold":   "Number of Persons usually resident Five Non family households",
	"Num_Psns_UR_5_Total":         "Number of Persons usually resident Five Total",
	"Num_Psns_UR_6mo_FamHhold":    "Number of Persons usually resident Six or more Family households",
	"Num_Psns_UR_6mo_NonFamHhold": "Number of Persons usually resident Six or more Non family households",
	"Num_Psns_UR_6mo_Total":       "Number of Persons usually resident Six or more Total",
	"Total_FamHhold":              "Total Family households",
	"Total_NonFamHhold":           "Total Non family households",
	"Total_Total":                 "Total Total",
}

//G59 Method of Travel to Work by Sex
var G59 = map[string]string{
	"One_method_Train_M":            "One method Train Males",
	"One_method_Train_F":            "One method Train Females",
	"One_method_Train_P":            "One method Train Persons",
	"One_method_Bus_M":              "One method Bus Males",
	"One_method_Bus_F":              "One method Bus Females",
	"One_method_Bus_P":              "One method Bus Persons",
	"One_method_Ferry_M":            "One method Ferry Males",
	"One_method_Ferry_F":            "One method Ferry Females",
	"One_method_Ferry_P":            "One method Ferry Persons",
	"One_met_Tram_incl_lt_rail_M":   "One method Tram includes light rail Males",
	"One_met_Tram_incl_lt_rail_F":   "One method Tram includes light rail Females",
	"One_met_Tram_incl_lt_rail_P":   "One method Tram includes light rail Persons",
	"One_method_Taxi_M":             "One method Taxi Males",
	"One_method_Taxi_F":             "One method Taxi Females",
	"One_method_Taxi_P":             "One method Taxi Persons",
	"One_method_Car_as_driver_M":    "One method Car as driver Males",
	"One_method_Car_as_driver_F":    "One method Car as driver Females",
	"One_method_Car_as_driver_P":    "One method Car as driver Persons",
	"One_method_Car_as_passenger_M": "One method Car as passenger Males",
	"One_method_Car_as_passenger_F": "One method Car as passenger Females",
	"One_method_Car_as_passenger_P": "One method Car as passenger Persons",
	"One_method_Truck_M":            "One method Truck Males",
	"One_method_Truck_F":            "One method Truck Females",
	"One_method_Truck_P":            "One method Truck Persons",
	"One_method_Motorbike_scootr_M": "One method Motorbike scooter Males",
	"One_method_Motorbike_scootr_F": "One method Motorbike scooter Females",
	"One_method_Motorbike_scootr_P": "One method Motorbike scooter Persons",
	"One_method_Bicycle_M":          "One method Bicycle Males",
	"One_method_Bicycle_F":          "One method Bicycle Females",
	"One_method_Bicycle_P":          "One method Bicycle Persons",
	"One_method_Other_M":            "One method Other Males",
	"One_method_Other_F":            "One method Other Females",
	"One_method_Other_P":            "One method Other Persons",
	"One_method_Walked_only_M":      "One method Walked only Males",
	"One_method_Walked_only_F":      "One method Walked only Females",
	"One_method_Walked_only_P":      "One method Walked only Persons",
	"One_method_Tot_one_method_M":   "One method Total one method Males",
	"One_method_Tot_one_method_F":   "One method Total one method Females",
	"One_method_Tot_one_method_P":   "One method Total one method Persons",
	"Two_methods_Train_Bus_M":       "Two methods Train and Bus Males",
	"Two_methods_Train_Bus_F":       "Two methods Train and Bus Females",
	"Two_methods_Train_Bus_P":       "Two methods Train and Bus Persons",
	"Two_methods_Train_Ferry_M":     "Two methods Train and Ferry Males",
	"Two_methods_Train_Ferry_F":     "Two methods Train and Ferry Females",
	"Two_methods_Train_Ferry_P":     "Two methods Train and Ferry Persons",
	"Two_mt_trn_Trm_incl_lt_rl_M":   "Two methods Train and Tram includes light rail Males",
	"Two_mt_trn_Trm_incl_lt_rl_F":   "Two methods Train and Tram includes light rail Females",
	"Two_mt_trn_Trm_incl_lt_rl_P":   "Two methods Train and Tram includes light rail Persons",
	"Two_methods_Trn_Car_as_drvr_M": "Two methods Train and Car as driver Males",
	"Two_methods_Trn_Car_as_drvr_F": "Two methods Train and Car as driver Females",
	"Two_methods_Trn_Car_as_drvr_P": "Two methods Train and Car as driver Persons",
	"Two_methods_Trn_Car_as_pass_M": "Two methods Train and Car as passenger Males",
	"Two_methods_Trn_Car_as_pass_F": "Two methods Train and Car as passenger Females",
	"Two_methods_Trn_Car_as_pass_P": "Two methods Train and Car as passenger Persons",
	"Two_methods_Train_Other_M":     "Two methods Train and Other Males",
	"Two_methods_Train_Other_F":     "Two methods Train and Other Females",
	"Two_methods_Train_Other_P":     "Two methods Train and Other Persons",
	"Two_methods_Train_Tot_M":       "Two methods Train and Total Males",
	"Two_methods_Train_Tot_F":       "Two methods Train and Total Females",
	"Two_methods_Train_Tot_P":       "Two methods Train and Total Persons",
	"Two_methods_Bus_Ferry_M":       "Two methods Bus and Ferry Males",
	"Two_methods_Bus_Ferry_F":       "Two methods Bus and Ferry Females",
	"Two_methods_Bus_Ferry_P":       "Two methods Bus and Ferry Persons",
	"Two_mth_Bu_Trm_inc_lt_rl_M":    "Two methods Bus and Tram includes light rail Males",
	"Two_mth_Bu_Trm_inc_lt_rl_F":    "Two methods Bus and Tram includes light rail Females",
	"Two_mth_Bu_Trm_inc_lt_rl_P":    "Two methods Bus and Tram includes light rail Persons",
	"Two_methods_Bus_Car_as_drvr_M": "Two methods Bus and Car as driver Males",
	"Two_methods_Bus_Car_as_drvr_F": "Two methods Bus and Car as driver Females",
	"Two_methods_Bus_Car_as_drvr_P": "Two methods Bus and Car as driver Persons",
	"Two_methods_Bus_Car_as_pass_M": "Two methods Bus and Car as passenger Males",
	"Two_methods_Bus_Car_as_pass_F": "Two methods Bus and Car as passenger Females",
	"Two_methods_Bus_Car_as_pass_P": "Two methods Bus and Car as passenger Persons",
	"Two_methods_Bus_Other_M":       "Two methods Bus and Other Males",
	"Two_methods_Bus_Other_F":       "Two methods Bus and Other Females",
	"Two_methods_Bus_Other_P":       "Two methods Bus and Other Persons",
	"Two_methods_Bus_Tot_M":         "Two methods Bus and Total Males",
	"Two_methods_Bus_Tot_F":         "Two methods Bus and Total Females",
	"Two_methods_Bus_Tot_P":         "Two methods Bus and Total Persons",
	"Two_methds_Othr_two_methds_M":  "Two methods Other two methods Males",
	"Two_methds_Othr_two_methds_F":  "Two methods Other two methods Females",
	"Two_methds_Othr_two_methds_P":  "Two methods Other two methods Persons",
	"Two_methods_Tot_two_methods_M": "Two methods Total two methods Males",
	"Two_methods_Tot_two_methods_F": "Two methods Total two methods Females",
	"Two_methods_Tot_two_methods_P": "Two methods Total two methods Persons",
	"Three_meth_Trn_two_othr_met_M": "Three methods Train and two other methods Males",
	"Three_meth_Trn_two_othr_met_F": "Three methods Train and two other methods Females",
	"Three_meth_Trn_two_othr_met_P": "Three methods Train and two other methods Persons",
	"Three_met_Bs_2_ot_met_ex_tr_M": "Three methods Bus and two other methods excludes train Males",
	"Three_met_Bs_2_ot_met_ex_tr_F": "Three methods Bus and two other methods excludes train Females",
	"Three_met_Bs_2_ot_met_ex_tr_P": "Three methods Bus and two other methods excludes train Persons",
	"Three_meth_Othr_three_meth_M":  "Three methods Other three methods Males",
	"Three_meth_Othr_three_meth_F":  "Three methods Other three methods Females",
	"Three_meth_Othr_three_meth_P":  "Three methods Other three methods Persons",
	"Three_meth_Tot_three_meth_M":   "Three methods Total three methods Males",
	"Three_meth_Tot_three_meth_F":   "Three methods Total three methods Females",
	"Three_meth_Tot_three_meth_P":   "Three methods Total three methods Persons",
	"Worked_home_M":                 "Worked at home Males",
	"Worked_home_F":                 "Worked at home Females",
	"Worked_home_P":                 "Worked at home Persons",
	"Did_not_go_to_work_M":          "Did not go to work Males",
	"Did_not_go_to_work_F":          "Did not go to work Females",
	"Did_not_go_to_work_P":          "Did not go to work Persons",
	"Method_travel_to_work_ns_M":    "Method of travel to work not stated Males",
	"Method_travel_to_work_ns_F":    "Method of travel to work not stated Females",
	"Method_travel_to_work_ns_P":    "Method of travel to work not stated Persons",
	"Tot_M":                         "Total Males",
	"Tot_F":                         "Total Females",
	"Tot_P":                         "Total Persons",
}
